<?php

namespace App\Utils;

class HmangaihaUtil
{
    public const APPLICATIONS = [
        'LEGAL_LICENCE_MANUFACTURING' => [
            'legal_name_manufcaturing',
            'legal_address',
            'legal_date_establishment',
            'legal_father_husband_name',
            'legal_current_registration_number',
            'legal_nature_manufacturing',
            'legal_type',
            'legal_type_weight',
            'legal_type_measures',
            'legal_type_weighing_instrument',
            'legal_type_measuring_instrument',
            'legal_number_of_emp',
            'legal_number_of_skilled_emp',
            'legal_number_of_semiskilled_emp',
            'legal_number_of_unskilled_emp',
            'legal_number_of_specialist',
            'legal_trademark',
            'legal_machinery_details',
            'legal_foundry_details',
            'legal_steel_facilities',
            'legal_electricity_availability',
            'legal_loan_received',
            'legal_bankers',
            'legal_TAX_number',
            'legal_previous_licence_application',
            'legal_item_proposed_selling',
            'legal_model_approved_details',

        ],
        'LEGAL_LICENCE_RENEWAL_MANUFACTURER' => [
            'legal_renewal_manufacturer_one',
            'legal_renewal_manufacturer_two',
            'legal_renewal_manufacturer_three',
            'legal_renewal_manufacturer_four_a',
            'legal_renewal_manufacturer_four_b',
            'legal_renewal_manufacturer_five',
            'legal_renewal_manufacturer_six',
            'legal_renewal_manufacturer_seven',
            'legal_renewal_manufacturer_eight',
            'legal_renewal_manufacturer_nine',
        ],
        'LEGAL_DEALER_RENEWAL' => [
            'legal_dealer_renewal_one',
            'legal_dealer_renewal_two',
            'legal_dealer_renewal_three',
            'legal_dealer_renewal_four',
            'legal_dealer_renewal_five',
            'legal_dealer_renewal_six',
            'legal_dealer_renewal_seven',
            'legal_dealer_renewal_eight',
        ],
        'LEGAL_LICENCE_REPAIR' => [
            'legal_licence_repair_one',
            'legal_licence_repair_two',
            'legal_licence_repair_three_a',
            'legal_licence_repair_three_b',
            'legal_licence_repair_four',
            'legal_licence_repair_five',
            'legal_licence_repair_six',
            'legal_licence_repair_seven',
            'legal_licence_repair_eight',
            'legal_licence_repair_nine',
            'legal_licence_repair_ten_1',
            'legal_licence_repair_ten_2',
            'legal_licence_repair_ten_3',
            'legal_licence_repair_ten_4',
            'legal_licence_repair_eleven',
            'legal_licence_repair_twelve',
            'legal_licence_repair_thirteen',
            'legal_licence_repair_fourteen',
        ],
        'LEGAL_LICENCE_DEALER' => [
            'legal_licence_dealer_one',
            'legal_licence_dealer_two',
            'legal_licence_dealer_three',
            'legal_licence_dealer_four',
            'legal_licence_dealer_five',
            'legal_licence_dealer_six',
            'legal_licence_dealer_seven',
            'legal_licence_dealer_eight_a',
            'legal_licence_dealer_eight_b',
            'legal_licence_dealer_nine',
        ],
        'LEGAL_REGISTRATION_MANUFACTURER_PACKER' => [

            'legal_registration_manufacturer_one',
            'legal_registration_manufacturer_two',
            'legal_registration_manufacturer_three',
            'legal_registration_manufacturer_four',
            'legal_registration_manufacturer_five',
            'legal_registration_manufacturer_six',
            'legal_registration_manufacturer_seven',
            'legal_registration_manufacturer_eight_from',
            'legal_registration_manufacturer_eight_to',
            'legal_registration_manufacturer_registration_no',
            'legal_registration_manufacturer_registration_year',

        ],
        'LEGAL_REGISTRATION_IMPORTER_PACKER' => [
            'legal_registration_importer_two',
            'legal_registration_importer_three',
            'legal_registration_importer_four',
            'legal_registration_importer_one',
            'legal_registration_importer_five',
            'legal_registration_importer_six',
            'legal_registration_importer_seven',
            'legal_registration_importer_eight',
            'legal_registration_importer_nine',

            'legal_registration_importer_nine_from',
            'legal_registration_importer_nine_to',
            'legal_registration_importer_registration_no',
            'legal_registration_importer_registration_year',

        ],
        'LEGAL_LICENCE_RENEWAL_REPAIRER' => [
            'legal_license_renewal_repairer_two',
            'legal_license_renewal_repairer_one',
            'legal_license_renewal_repairer_three',
            'legal_license_renewal_repairer_four',
            'legal_license_renewal_repairer_five',
            'legal_license_renewal_repairer_six_a',
            'legal_license_renewal_repairer_six_b',
            'legal_license_renewal_repairer_seven',
            'legal_license_renewal_repairer_eight',
            'legal_license_renewal_repairer_nine',

        ],
        'LEGAL_LICENCE_REGISTRATION_IMPORTER' => [
            'legal_licence_registration_importer_one',
            'legal_licence_registration_importer_two',
            'legal_licence_registration_importer_three',
            'legal_licence_registration_importer_four',
            'legal_licence_registration_importer_five',
            'legal_licence_registration_importer_five_a',
            'legal_licence_registration_importer_five_b',
            'legal_licence_registration_importer_six',
            'legal_licence_registration_importer_seven',
            'legal_licence_registration_importer_eight',
            'legal_licence_registration_importer_nine',
            'legal_licence_registration_importer_registration_fee',
            'legal_licence_registration_importer_registration_place',
            'legal_licence_registration_importer_registration_chalan_no',
            'legal_licence_registration_importer_registration_dated',

        ],
        'LEGAL_VERIFICATION' => [
            'legal_verifcation_officer_name',
            'legal_verification_no',
            'legal_verification_belongs_to',
            'legal_verification_locality',
            'legal_verification_one',
            'legal_verification_two',
            'legal_verification_two_a',
            'legal_verification_two_b',
            'legal_verification_three',
            'legal_verification_three_a',
            'legal_verification_three_b',
            'legal_verification_three_c',
            'legal_verification_three_d',
            'legal_verification_four',
            'legal_verification_five',
            'legal_verification_six',
            'legal_verification_deposited_amount',
            'legal_verification_deposited_receipt_No',
            'legal_verification_deposted_date',

        ],
        'LEGAL_REVERIFICATION' => [
            'legal_reverifcation_officer_name',
            'legal_reverification_no',
            'legal_reverification_belongs_to',
            'legal_reverification_locality',
            'legal_reverification_one',
            'legal_reverification_two',
            'legal_reverification_two_a',
            'legal_reverification_two_b',
            'legal_reverification_three',
            'legal_reverification_three_a',
            'legal_reverification_three_b',
            'legal_reverification_three_c',
            'legal_reverification_three_d',
            'legal_reverification_four',
            'legal_reverification_five',
            'legal_reverification_six',
            'legal_reverification_deposited_amount',
            'legal_reverification_deposited_receipt_No',
            'legal_reverification_deposted_date',

        ],

        // POLLUTION

        'POLLUTION_RETURN_SALE_BATTERY' => [
            'pollution_return_sale_battery_one',
            'pollution_return_sale_battery_two',
            'pollution_return_sale_battery_three_i_a_i',
            'pollution_return_sale_battery_three_i_a_ii',
            'pollution_return_sale_battery_three_i_b_i',
            'pollution_return_sale_battery_three_i_b_ii',
            'pollution_return_sale_battery_three_ii_a_i',
            'pollution_return_sale_battery_three_ii_a_ii',
            'pollution_return_sale_battery_three_ii_b_i',
            'pollution_return_sale_battery_three_ii_b_ii',
            'pollution_return_sale_battery_three_ii_c_i',
            'pollution_return_sale_battery_three_ii_c_ii',
            'pollution_return_sale_battery_three_ii_d_i',
            'pollution_return_sale_battery_three_ii_d_ii',
            'pollution_return_sale_battery_three_iii_a_i',
            'pollution_return_sale_battery_three_iii_a_ii',
            'pollution_return_sale_battery_three_iii_b_i',
            'pollution_return_sale_battery_three_iii_b_ii',
            'pollution_return_sale_battery_three_iii_c_i',
            'pollution_return_sale_battery_three_iii_c_ii',
            'pollution_return_sale_battery_three_iii_d_i',
            'pollution_return_sale_battery_three_iii_d_ii:',
            'pollution_return_sale_battery_four',
        ],
        'POLLUTION_AUTHORIZATION_GENERATION_OR_STORAGE' => [
            'pollution_authorization_generation_one',
            'pollution_authorization_generation_two',
            'pollution_authorization_generation_three_i',
            'pollution_authorization_generation_three_ii',
            'pollution_authorization_generation_three_iii',
            'pollution_authorization_generation_three_iv',
            'pollution_authorization_generation_four_a',
            'pollution_authorization_generation_four_b',
            'pollution_authorization_generation_four_c',
            'pollution_authorization_generation_four_d',
            'pollution_authorization_generation_five',
            'pollution_authorization_generation_six',
        ],
        'POLLUTION_AUTHORIZATION_EWASTE' => [
            'pollution_authorization_ewaste_one',
            'pollution_authorization_ewaste_two',
            'pollution_authorization_ewaste_three_i',
            'pollution_authorization_ewaste_three_ii',
            'pollution_authorization_ewaste_three_iii',
            'pollution_authorization_ewaste_three_iv',
            'pollution_authorization_ewaste_four_a',
            'pollution_authorization_ewaste_four_b',
            'pollution_authorization_ewaste_four_c',
            'pollution_authorization_ewaste_four_d',
            'pollution_authorization_ewaste_five',
            'pollution_authorization_ewaste_six',
        ],

        'POLLUTION_AUTHORIZATION_BIO_WASTE' => [
            'pollution_authorization_bio_waste_one_1',
            'pollution_authorization_bio_waste_one_2',
            'pollution_authorization_bio_waste_two_1',
            'pollution_authorization_bio_waste_two_2',
            'pollution_authorization_bio_waste_two_activity_1',
            'pollution_authorization_bio_waste_two_activity_2',
            'pollution_authorization_bio_waste_two_activity_3',
            'pollution_authorization_bio_waste_two_activity_4',
            'pollution_authorization_bio_waste_two_activity_5',
            'pollution_authorization_bio_waste_two_activity_6',
            'pollution_authorization_bio_waste_two_activity_7',
            'pollution_authorization_bio_waste_two_activity_8',
            'pollution_authorization_bio_waste_two_activity_9',
            'pollution_authorization_bio_waste_two_activity_10',
            'pollution_authorization_bio_waste_two_activity_11',
            'pollution_authorization_bio_waste_two_activity_12',
            'pollution_authorization_bio_waste_three',
            'pollution_authorization_bio_waste_three_1',
            'pollution_authorization_bio_waste_three_2',
            'pollution_authorization_bio_waste_three_3',
            'pollution_authorization_bio_waste_three_4',
            'pollution_authorization_bio_waste_three_5',
            'pollution_authorization_bio_waste_category_1',
            'pollution_authorization_bio_waste_category_2',
            'pollution_authorization_bio_waste_category_3',
            'pollution_authorization_bio_waste_category_4',
            'pollution_authorization_bio_waste_category_5',
            'pollution_authorization_bio_waste_category_6',
        ],
        'POLLUTION_AUTHORIZATION_FACILITIES' => [
            'pollution_authorization_facilities_one_i',
            'pollution_authorization_facilities_one_ii',
            'pollution_authorization_facilities_two_i',
            'pollution_authorization_facilities_two_ii',
            'pollution_authorization_facilities_three',
            'pollution_authorization_facilities_four',
            'pollution_authorization_facilities_five_i',
            'pollution_authorization_facilities_five_ii',
            'pollution_authorization_facilities_six',
            'pollution_authorization_facilities_seven',
            'pollution_authorization_facilities_eight_i',
            'pollution_authorization_facilities_eight_ii',
            'pollution_authorization_facilities_nine_i',
            'pollution_authorization_facilities_nine_ii',
            'pollution_authorization_facilities_nine_iii',
            'pollution_authorization_facilities_ten_i',
            'pollution_authorization_facilities_ten_ii',
            'pollution_authorization_facilities_ten_iii',
            'pollution_authorization_facilities_eleven',
            'pollution_authorization_facilities_twelve',
            'pollution_authorization_facilities_thirteen',
            'pollution_authorization_facilities_fourteen',
            'pollution_authorization_facilities_fifteen',
            'pollution_authorization_facilities_sixteen',
            'pollution_authorization_facilities_seventeen',
            'pollution_authorization_facilities_eighteen',
            'pollution_authorization_facilities_nineteen',
            'pollution_authorization_facilities_twenty',
            'pollution_authorization_facilities_twentyone',

        ],

        // COMMERCE and INDUSTRIES
        // 11
        'CE_GRANT_OF_SUBSIDY' => [
            'ce_grant_of_subsidy_one',
            'ce_grant_of_subsidy_two',
            'ce_grant_of_subsidy_three',
            'ce_grant_of_subsidy_four',
            'ce_grant_of_subsidy_five_a',
            'ce_grant_of_subsidy_five_b',
            'ce_grant_of_subsidy_six',
            'ce_grant_of_subsidy_seven',
            'ce_grant_of_subsidy_eight',
            'ce_grant_of_subsidy_nine',
            'ce_grant_of_subsidy_ten_a',
            'ce_grant_of_subsidy_ten_b',
            'ce_grant_of_subsidy_eleven',
            'ce_grant_of_subsidy_twelve',
        ],
        // 10
        'C&E_SUBSIDY_COST_TRANSPORTATION_MACHINERIES' => [
            'commerce_subsidy_cost_transportation_one',
            'commerce_subsidy_cost_transportation_two',
            'commerce_subsidy_cost_transportation_two_a',
            'commerce_subsidy_cost_transportation_two_b',
            'commerce_subsidy_cost_transportation_three',
            'commerce_subsidy_cost_transportation_four',
            'commerce_subsidy_cost_transportation_five',
            'commerce_subsidy_cost_transportation_six',
            'commerce_subsidy_cost_transportation_seven',
            'commerce_subsidy_cost_transportation_eight',
            'commerce_subsidy_cost_transportation_eight_a',
            'commerce_subsidy_cost_transportation_eight_b',
            'commerce_subsidy_cost_transportation_eight_c',
            'commerce_subsidy_cost_transportation_nine',
            'commerce_subsidy_cost_transportation_nine_a',
            'commerce_subsidy_cost_transportation_nine_b',
            'commerce_subsidy_cost_transportation_ten',
            'commerce_subsidy_cost_transportation_ten_a',
            'commerce_subsidy_cost_transportation_ten_b',
            'commerce_subsidy_cost_transportation_ten_c',
            'commerce_subsidy_cost_transportation_eleven',
        ],
        // POWER
        "POWER_CONNECTED_LOAD"=>[
            'power_connected_load_one',
            'power_connected_load_two',
            'power_connected_load_three',
            'power_connected_load_four:', 
            'power_connected_load_t1',
            'power_connected_load_t2',
            'power_connected_load_t3',
            'power_connected_load_t4',
            'power_connected_load_t5',
            'power_connected_load_t6',
            'power_connected_load_t7',
            'power_connected_load_t8',
            'power_connected_load_t9',
            'power_connected_load_t10',
            'power_connected_load_t11',
            'power_connected_load_t12',
            'power_connected_load_t13',
            'power_connected_load_t14',
            'power_connected_load_t15',
            'power_connected_load_t16',
            'power_connected_load_t17',
            'power_connected_load_t18',
            'power_connected_load_t_total',
        ]



    ];


    public const LABELS = [
        'legal_name_manufcaturing' => "1.Name of the manufacturing concern for which licence is desired.",
        'legal_address' => "2.Complete address of the concern. Whether premises are
        owned/rented/taken on lease/leave licence, duly supported by documents.",
        'legal_date_establishment' => "3. Date of Establishment of workshop/factory.",
        'legal_father_husband_name' => " 4. Name (s) and address (s) along with their father's/ husband's name
        of proprietor (s) and/or Partners and Managing Director (s) in the
        case of Limited company",
        'legal_current_registration_number' => " 5. The date and current registration number of factory/ shop/
        establishment/ Municipal Trade licence.",
        'legal_nature_manufacturing' => "6. Nature of manufacturing activities at present.",
        'legal_type' => "7. The type of weights and measures proposed to be manufactured viz",
        'legal_type_weight' => "(i) Weights",
        'legal_type_measures' => "(ii) Measures",
        'legal_type_weighing_instrument' => "(iii) Weighing Instruments",
        'legal_type_measuring_instrument' => "(iv) Measuring Instruments with details in each case.",
        'legal_number_of_emp' => "8. The number of persons employed/proposed to be employed",
        'legal_number_of_skilled_emp' => " (i) Skilled",
        'legal_number_of_semiskilled_emp' => "(ii) Semi-skilled",
        'legal_number_of_unskilled_emp' => "(iii) Unskilled",
        'legal_number_of_specialist' => "(iv) Specialist trained in the line",
        'legal_trademark' => " 9. The monogram or trade mark intended to be Imprinted on weights and
        measures to be manufactured",
        'legal_machinery_details' => "10. Details of machinery, tools accessories, owned and used for
        manufacturing weights measures etc.",
        'legal_foundry_details' => "11. Details of foundry/workshop facilities arranged. Whether ownership,
        long term lease etc.",
        'legal_steel_facilities' => "12. Facilities of steel casting and hardness testing of Vital parts etc
        or other means.",
        'legal_electricity_availability' => "13. Availability of electric energy.",
        'legal_loan_received' => "14. Details of loan received from Government or financial Institution.
        If so, give details.",
        'legal_bankers' => "15. Name of bankers, if any.",
        'legal_TAX_number' => "16. VAT/ Sales Tax Registration Number/CST Number/ Professional Tax
        registration Number/IT Number.",
        'legal_previous_licence_application' => "17. Have you applied previously for a manufacturer's licence? If so,
        when and with what results ?",
        'legal_item_proposed_selling' => " (a) Whether the item (s) proposed to be manufactured will be sold
        within the State or out side the state or both.",
        'legal_model_approved_details' => "(b) Details of Model Approval received from Government of India.
        When can you produce for inspection samples of your products for
        which licence is desired ?",


        //legal licence renewal manufacturer
        'legal_renewal_manufacturer_one' => "1. Name and complete address of the manufacturing concern for which renewal_manufacturer of licence is desired.",
        'legal_renewal_manufacturer_two' => "2. Manufacturing Licence No.",
        'legal_renewal_manufacturer_three' => "3. Name (s) and address (s) along with their father's/husband's name of proprietor (s) and/or Partners and Managing Director (s) in the case of Limited company",
        'legal_renewal_manufacturer_four_a' => "(a) Type of weights and measures which are manufactured as per licence granted.",
        'legal_renewal_manufacturer_four_b' => "(b) Do you propose any change.",
        'legal_renewal_manufacturer_five' => " 5. The monogram or trade marks used on weights and measures manufactured by yo",
        'legal_renewal_manufacturer_six' => " 6. Details of workshop facilities available. ",
        'legal_renewal_manufacturer_seven' => "7. Details of production and sales in the last 5 years.",
        'legal_renewal_manufacturer_eight' => "8. Number and date of shop/establishment Registration Number.",
        'legal_renewal_manufacturer_nine' => "9. Registration Number of VAT/Sales Tax/CST/Professional Tax/Income Tax.",

        // legal dealer renewal
        'legal_dealer_renewal_one' => "1. Name of the establishment/shop/person seeking the renewal of licence",
        'legal_dealer_renewal_two' => "2. Dealer's Licence Number.",
        'legal_dealer_renewal_three' => "3. Date of establishment.",
        'legal_dealer_renewal_four' => " 4. Name (s) and address (s) along with their father's/ husband's name of proprietor (s) and/or Partners and Managing Director (s) in the case of Limited company",
        'legal_dealer_renewal_five' => "5. Registration Number and date of shop/establishment/ current Municipal Trade Licence.",
        'legal_dealer_renewal_six' => "6. Categories of weights and measures sold at present",
        'legal_dealer_renewal_seven' => "7. Registration Number of VAT/ CST/Sales Tax/Professional Tax/Income Tax.",
        'legal_dealer_renewal_eight' => "8. Are you intending to import weights and measures etc.
        from places outside the State/Country? If so, indicate
        sources of supply from the State (s)/Country (s).
        (Give details of manufacturer's trade mark/ monogram
        and his licence number.)",

        // legal licence repair
        'legal_licence_repair_one' => "1. Name of the concern seeking the licence.",
        'legal_licence_repair_two' => "2. Complete address of the workshop.",
        'legal_licence_repair_three_a' => "(a) Whether premises are owned/rented/taken. on lease dully supported by documents.",
        'legal_licence_repair_three_b' => "(b) Date of establishment.",
        'legal_licence_repair_four' => " 4. Name (s) and address (s) along with their father's/ husband's name of proprietor (s) and/or Partners and
        Managing Director (s) in the case of Limited company.",
        'legal_licence_repair_five' => "5. Number and date of shop/establishment/current 
        Municipal Trade Licence.",
        'legal_licence_repair_six' => "  6. Professional Tax/IT Tax registration Number etc if any.",
        'legal_licence_repair_seven' => "7. The type of weights and measures proposed to repaired.",
        'legal_licence_repair_eight' => "8. Area in which you wish to operate",
        'legal_licence_repair_nine' => "9. Previous experience in the line.",
        'legal_licence_repair_ten' => "10. Number of skilled staff employed or proposed to be employed:",
        'legal_licence_repair_ten_1' => "(i) Skilled",
        'legal_licence_repair_ten_2' => "(ii) Semi-skilled",
        'legal_licence_repair_ten_3' => "(iii) Unskilled",
        'legal_licence_repair_ten_4' => "(iv) Employees trained in the line",
        'legal_licence_repair_eleven' => "11. Details of machinery/tools/accessories available.",
        'legal_licence_repair_twelve' => "12. Availability of electric energy.",
        'legal_licence_repair_thirteen' => "13. Have you sufficient stock of loan/test weights. etc.? Give details",
        'legal_licence_repair_fourteen' => "14. Have you applied previously for a repairer's licence?
        If so, When and with what results?",


        // legal licence dealer
        'legal_licence_dealer_one' => "1. Name of the establishment/shop/person seeking the licence.",
        'legal_licence_dealer_two' => "2. Complete address of the establishment etc.",
        'legal_licence_dealer_three' => "3. Date of establishment.",
        'legal_licence_dealer_four' => "4. Name (s) and address (s) along with their father's/ husband's name of proprietor (s) and/or Partners and Managing Director (s) in the case of Limited company",
        'legal_licence_dealer_five' => "5. Number and date of Registration Number of current shop/establishment/Municipal Trade licence",
        'legal_licence_dealer_six' => "6. Categories of weights and measures sold/proposed to be sold at present",
        'legal_licence_dealer_seven' => "7. Registration Number of VAT/ CST/Sales Tax/Professional Tax/Income Tax.",
        'legal_licence_dealer_eight_a' => "(a) Registration of Importer of Weights and Measures, if any",
        'legal_licence_dealer_eight_b' => "(b) Approval of model imported into India by Central Government",
        'legal_licence_dealer_nine' => "9. Have you applied previously for a dealer's licence,either in this State or elsewhere ? If so give details ?",

        //Legal registration Manufacturer and PACKER
        'legal_registration_manufacturer_one' => "1. Name",
        'legal_registration_manufacturer_two' => "2. Complete Address",
        'legal_registration_manufacturer_three' => "3. Aadhaar number",
        'legal_registration_manufacturer_four' => "4. Address of warehouse",
        'legal_registration_manufacturer_five' => "5. Type of Commodities to be manufactured or packed",
        'legal_registration_manufacturer_six' => "6. Area of Operation",
        'legal_registration_manufacturer_seven' => "7. Date of Registration",
        'legal_registration_manufacturer_eight' => "8. This Registration is valid",
        'legal_registration_manufacturer_eight_from' => "From",
        'legal_registration_manufacturer_eight_to' => "to",
        'legal_registration_manufacturer_registration_no' => "Registration no.",
        'legal_registration_manufacturer_registration_year' => "of Year",

        //Legal Registration Manufacturer and Importer
        'legal_registration_importer_one' => "1. Name",
        'legal_registration_importer_two' => "2. Complete Address ",
        'legal_registration_importer_three' => "3. Aadhaar number",
        'legal_registration_importer_four' => "4. Address of warehouse",
        'legal_registration_importer_five' => "5. Type of Commodities to be packed or to imported",
        'legal_registration_importer_six' => "6. No. of IEC / Licence with date",
        'legal_registration_importer_seven' => "7. Area of Operation",
        'legal_registration_importer_eight' => "8. Date of Registration",
        'legal_registration_importer_nine' => "9. This Registration is valid",
        'legal_registration_importer_nine_from' => "From",
        'legal_registration_importer_nine_to' => "to",
        'legal_registration_importer_registration_no' => " Registration no.",
        'legal_registration_importer_registration_year' => "Year",

        // legal licence renewal repair
        'legal_license_renewal_repairer_two' => "1. Name and complete address of the repairing concern/ person seeking  renewal of the licence .",
        'legal_license_renewal_repairer_one' => "2. Repairer's Licence Number.",
        'legal_license_renewal_repairer_three' => "3. Name (s) and address (s) along with their father's/ husband's name of proprietor (s) and/or Partners and Managing Director (s) in the case of Limited company.",
        'legal_license_renewal_repairer_four' => "4. Registration Number and date of current shop/ establishment/Municipal Trade Licence.",
        'legal_license_renewal_repairer_five' => " 5. Registration Number of VAT/ Sales Tax/CST/Professional Tax/Income Tax",
        'legal_license_renewal_repairer_six_a' => "(a) The Type of weights and measures repaired as per licence granted",
        'legal_license_renewal_repairer_six_b' => "(b) Do you propose any change?",
        'legal_license_renewal_repairer_seven' => "7. Area in which you are operating.",
        'legal_license_renewal_repairer_eight' => "8. Have you sufficient stock of loan/test weights, etc.?",
        'legal_license_renewal_repairer_nine' => "9. Please give details with particulars of stamping.",

        // LEGAL_LICENCE_REGISTRATION_IMPORTER
        'legal_licence_registration_importer_one' => "1. Name and full address",
        'legal_licence_registration_importer_two' => "2. Whether individual/undivided Hindu family/registered firm",
        'legal_licence_registration_importer_three' => "3.Income-tax registration No( If any)",
        'legal_licence_registration_importer_four' => "4.Date of registration as manufacturer/dealer;registration No. and name of  registry authority",
        'legal_licence_registration_importer_five' => "5.Date & No. of licence to carry on the business of weights and measures;the name of authority by whom the licence was issued/renewed",
        'legal_licence_registration_importer_five_a' => "(a)buying and selling ,or",
        'legal_licence_registration_importer_five_b' => "(b) manufacturing",
        'legal_licence_registration_importer_six' => "6.Item(s) of weights and measures in relation to which the applicant has been registered as manufacturer and/or dealer",
        'legal_licence_registration_importer_seven' => "7.Items of weights and measures for which the applicant is being made for registration as importer",
        'legal_licence_registration_importer_eight' => "8.Items,if any,imported during the period of two years immediately preceding the year in which the application is made:",
        'legal_licence_registration_importer_nine' => "9.Remarks",
        'legal_licence_registration_importer_registration_fee' => "Registration fee",
        'legal_licence_registration_importer_registration_place' => "Paid in the treasury at",
        'legal_licence_registration_importer_registration_chalan_no' => "Chalan No.",
        'legal_licence_registration_importer_registration_dated' => "Dated",

        // legal verification
        'legal_verifcation_officer_name' => "Name of Legal Metrology Officer",
        'legal_verification_no' => "No.",
        'legal_verification_belongs_to' => "Belongs to",
        'legal_verification_locality' => "Locality",
        'legal_verification_one' => "1.Quantity",
        'legal_verification_two' => "Denomination",
        'legal_verification_two_a' => "i.Weights",
        'legal_verification_two_b' => "ii.Measures",
        'legal_verification_three' => "Weighing instruments",
        'legal_verification_three_a' => "i.Capacity",
        'legal_verification_three_b' => "ii.Class",
        'legal_verification_three_c' => "iii.Manufacturer",
        'legal_verification_three_d' => "iv. Type",
        'legal_verification_four' => "4.Measuring Instruments",
        'legal_verification_five' => "5. Verification fee",
        'legal_verification_six' => "6.Carriage,conveyance adjusting charges etc.",
        'legal_verification_deposited_amount' => "Total amount (Rs.) deposited",
        'legal_verification_deposited_receipt_No' => "T. Receipt/ Money receipt .No",
        'legal_verification_deposted_date' => "Dated",

        // legal reverification
        'legal_reverifcation_officer_name' => "Name of Legal Metrology Officer",
        'legal_reverification_no' => "No.",
        'legal_reverification_belongs_to' => "Belongs to",
        'legal_reverification_locality' => "Locality",
        'legal_reverification_one' => "1.Quantity",
        'legal_reverification_two' => "Denomination",
        'legal_reverification_two_a' => "i.Weights",
        'legal_reverification_two_b' => "ii.Measures",
        'legal_reverification_three' => "Weighing instruments",
        'legal_reverification_three_a' => "i.Capacity",
        'legal_reverification_three_b' => "ii.Class",
        'legal_reverification_three_c' => "iii.Manufacturer",
        'legal_reverification_three_d' => "iv. Type",
        'legal_reverification_four' => "4.Measuring Instruments",
        'legal_reverification_five' => "5. Verification fee",
        'legal_reverification_six' => "6.Carriage,conveyance adjusting charges etc.",
        'legal_reverification_deposited_amount' => "Total amount (Rs.) deposited",
        'legal_reverification_deposited_receipt_No' => "T. Receipt/ Money receipt .No",
        'legal_reverification_deposted_date' => "Dated",


        // POLLTUION
        // pollution return sale battery
        'pollution_return_sale_battery_one' => "1. Name and address of the dealer",
        'pollution_return_sale_battery_two' => "2. Name of the authorised person and complete address with telephone and fax numbers",
        'pollution_return_sale_battery_three' => "3.Number of new batteries sold during the period October-March/April-September in respect of the  following categories ",
        'pollution_return_sale_battery_three_category' => "Category",
        'pollution_return_sale_battery_three_i:' => "Automative",
        'pollution_return_sale_battery_three_i_a_i' => "No. of batteries",
        'pollution_return_sale_battery_three_i_a_ii' => "Approximate weight in Metric Tones",
        'pollution_return_sale_battery_three_i_b_i' => "No. of batteries",
        'pollution_return_sale_battery_three_i_b_ii' => "Approximate weight in Metric Tones",
        'pollution_return_sale_battery_three_ii:' => "Industrial",
        'pollution_return_sale_battery_three_ii_a_i' => "No. of batteries",
        'pollution_return_sale_battery_three_ii_a_ii' => "Approximate weight in Metric Tones",
        'pollution_return_sale_battery_three_ii_b_i' => "No. of batteries",
        'pollution_return_sale_battery_three_ii_b_ii' => "Approximate weight in Metric Tones",
        'pollution_return_sale_battery_three_ii_c_i' => "No. of batteries",
        'pollution_return_sale_battery_three_ii_c_ii' => "Approximate weight in Metric Tones",
        'pollution_return_sale_battery_three_ii_d_i' => "No. of batteries",
        'pollution_return_sale_battery_three_ii_d_ii' => "Approximate weight in Metric Tones",
        'pollution_return_sale_battery_three_iii:' => "Number of batteries sold",
        'pollution_return_sale_battery_three_iii_a_i' => "No. of batteries",
        'pollution_return_sale_battery_three_iii_a_ii' => "Approximate weight in Metric Tones",
        'pollution_return_sale_battery_three_iii_b_i' => "No. of batteries",
        'pollution_return_sale_battery_three_iii_b_ii' => "Approximate weight in Metric Tones",
        'pollution_return_sale_battery_three_iii_c_i' => "No. of batteries",
        'pollution_return_sale_battery_three_iii_c_ii' => "Approximate weight in Metric Tones",
        'pollution_return_sale_battery_three_iii_d_i' => "No. of batteries",
        'pollution_return_sale_battery_three_iii_d_ii:' => "Approximate weight in Metric Tones",
        'pollution_return_sale_battery_four' => "4. Total number of used batteries of different categories as at Sl. No. 3 collected and sent to registered recyclers * / designated collection centers / manufacturers",

        // pollution authorization generation or storage 
        'pollution_authorization_generation_one' => " 1. Name and full address",
        'pollution_authorization_generation_two' => "2. Contact Person with designation and contact details such as telephone Nos, Fax. No. and E-mail:",
        'pollution_authorization_generation_three' => "3. Authorisation required for (Please tick mark appropriate activity/ies*) ",
        'pollution_authorization_generation_three_i' => "(i) Generation during manufacturing or refurbishing",
        'pollution_authorization_generation_three_ii' => "(ii) Treatment, if any",
        'pollution_authorization_generation_three_iii' => "(iii) Collection, Transportation, Storage",
        'pollution_authorization_generation_three_iv' => "(iv) Refurbishing",
        'pollution_authorization_generation_four' => "4. E-waste details:",
        'pollution_authorization_generation_four_a' => "(a) Total quantity e-waste generated in MT/A ",
        'pollution_authorization_generation_four_b' => "(b) Quantity refurbished (applicable to refurbisher)",
        'pollution_authorization_generation_four_c' => " (c) Quantity sent for recycling",
        'pollution_authorization_generation_four_d' => "(d) Quantity sent for disposal ",
        'pollution_authorization_generation_five' => " 5. Details of Facilities for storage/handling/treatment/refurbishing",
        'pollution_authorization_generation_six' => "6. In case of renewal of authorisation previous authorisation no. and date and details of annual returns",

        // pollution authorization ewaste
        'pollution_authorization_ewaste_one' => " 1. Name and full address",
        'pollution_authorization_ewaste_two' => "2. Contact Person with designation and contact details such as telephone Nos, Fax. No. and E-mail:",
        'pollution_authorization_ewaste_three' => "3. Authorisation required for (Please tick mark appropriate activity/ies*) ",
        'pollution_authorization_ewaste_three_i' => "(i) Generation during manufacturing or refurbishing",
        'pollution_authorization_ewaste_three_ii' => "(ii) Treatment, if any",
        'pollution_authorization_ewaste_three_iii' => "(iii) Collection, Transportation, Storage",
        'pollution_authorization_ewaste_three_iv' => "(iv) Refurbishing",
        'pollution_authorization_ewaste_four' => "4. E-waste details:",
        'pollution_authorization_ewaste_four_a' => "(a) Total quantity e-waste generated in MT/A ",
        'pollution_authorization_ewaste_four_b' => "(b) Quantity refurbished (applicable to refurbisher)",
        'pollution_authorization_ewaste_four_c' => " (c) Quantity sent for recycling",
        'pollution_authorization_ewaste_four_d' => "(d) Quantity sent for disposal ",
        'pollution_authorization_ewaste_five' => " 5. Details of Facilities for storage/handling/treatment/refurbishing",
        'pollution_authorization_ewaste_six' => "6. In case of renewal of authorisation previous authorisation no. and date and details of annual returns",


        // pollution bio waste
        'pollution_authorization_bio_waste_one_1' => "1.Authorization no:",
        'pollution_authorization_bio_waste_one_2' => "Authorization issue date",
        'pollution_authorization_bio_waste_two_1' => "2.Occuppier/Operator ",
        'pollution_authorization_bio_waste_two_2' => "Facility Location",
        'pollution_authorization_bio_waste_two_activity_1' => "Generation, segregation",
        'pollution_authorization_bio_waste_two_activity_2' => "Collection",
        'pollution_authorization_bio_waste_two_activity_3' => "Storage",
        'pollution_authorization_bio_waste_two_activity_4' => "Packaging",
        'pollution_authorization_bio_waste_two_activity_5' => "Reception",
        'pollution_authorization_bio_waste_two_activity_6' => "Transportation",
        'pollution_authorization_bio_waste_two_activity_7' => "Treatment or processing or conversion",
        'pollution_authorization_bio_waste_two_activity_8' => "Recycling",
        'pollution_authorization_bio_waste_two_activity_9' => "Disposal or destruction ",
        'pollution_authorization_bio_waste_two_activity_10' => "Use",
        'pollution_authorization_bio_waste_two_activity_11' => "Offering for sale, transfer",
        'pollution_authorization_bio_waste_two_activity_12' => "Any other form of handling",
        'pollution_authorization_bio_waste_three' => "",
        'pollution_authorization_bio_waste_three_1' => "(i) Number of beds of HCF",
        'pollution_authorization_bio_waste_three_2' => "(ii) Number healthcare facilities covered by CBMWTF:",
        'pollution_authorization_bio_waste_three_3' => "(iii) Installed treatment and disposal capacity",
        'pollution_authorization_bio_waste_three_4' => "(iv) Area or distance covered by CBMWTF",
        'pollution_authorization_bio_waste_three_5' => " (v) Quantity of Biomedical waste handled, treated or disposed:",
        'pollution_authorization_bio_waste_category_1' => "Yellow",
        'pollution_authorization_bio_waste_category_2' => "Red",
        'pollution_authorization_bio_waste_category_3' => "White (Translucent)",
        'pollution_authorization_bio_waste_category_4' => "Blue",
        'pollution_authorization_bio_waste_category_5' => "Puncture Proof, leak proof, tamper proof containers",
        'pollution_authorization_bio_waste_category_6' => "Cardboard boxes with blue colored marking",

        //   pollution authorization facilities
        'pollution_authorization_facilities_one_i' => "(i) Name Of The Unit",
        'pollution_authorization_facilities_one_ii' => "(ii) Address Of The Unit",
        'pollution_authorization_facilities_two_i' => "(i) Contact Person Name",
        'pollution_authorization_facilities_two_ii' => "(ii) Designation",
        'pollution_authorization_facilities_three' => "3. Date Of Commissioning",
        'pollution_authorization_facilities_four' => "4. No Of Workers (including Contract Labour)",
        'pollution_authorization_facilities_five_i' => "(i) Water (Prevention And Control Of Pollution) Act, 1974; Valid Up To",
        'pollution_authorization_facilities_five_ii' => "(ii) Air (Prevention And Control Of Pollution) Act, 1981;Valid Up To",
        'pollution_authorization_facilities_six' => "6. Validity Of Current Authorisation If Any",
        'pollution_authorization_facilities_seven' => "7. Dismantling Or Recycling Process , Please Attach Complete Details",
        'pollution_authorization_facilities_eight_i' => "(i) Products",
        'pollution_authorization_facilities_eight_ii' => "(ii) Installed Capacity (MTA)",
        'pollution_authorization_facilities_nine_i' => "(i) Year",
        'pollution_authorization_facilities_nine_ii' => "(ii) Product",
        'pollution_authorization_facilities_nine_iii' => "(iii) Quantity",
        'pollution_authorization_facilities_ten_i' => "(i) Waste Generation In Processing E-waste",
        'pollution_authorization_facilities_ten_ii' => "(ii) Provide Details Of Disposal Of Residue",
        'pollution_authorization_facilities_ten_iii' => "(iii) Name Of Treatment Storage And Disposal Facility Utilized For",
        'pollution_authorization_facilities_eleven' => "11. Details Of E-waste Proposed To Be Procured From Re-processing",
        'pollution_authorization_facilities_twelve' => "12. Details Of E-waste Proposed To Be Procured From Re-processing",
        'pollution_authorization_facilities_thirteen' => "13. Details Of Facilities For Dismantling Both Manual As Well As Mechanised",
        'pollution_authorization_facilities_fourteen' => "14. Upload Of Agreement With Collection Centre",
        'pollution_authorization_facilities_fifteen' => "15. Upload Agreement With Producer",
        'pollution_authorization_facilities_sixteen' => "16. Details Of Storage For Dismantled E-waste",
        'pollution_authorization_facilities_seventeen' => "17. Upload Of Agreement With Recycler",
        'pollution_authorization_facilities_eighteen' => "18. Details Of Facilities For Recycling",
        'pollution_authorization_facilities_nineteen' => "19. Upload Of Agreement With Collection Centre",
        'pollution_authorization_facilities_twenty' => "20. Upload Agreement With Producer",
        'pollution_authorization_facilities_twentyone' => "21. Details Of Storage For Raw Materials And Recovered Materials",


        // COMMERCE and INDUSTRIES

        'ce_grant_of_subsidy_one' => "1. Name and Address of Industrial unit",
        'ce_grant_of_subsidy_two' => "2. Detail address stating Plot no./Land No. ",
        'ce_grant_of_subsidy_three' => "3. Registration No. ",
        'ce_grant_of_subsidy_four' => "4. Total space area of land alloted with order No. & date ",
        'ce_grant_of_subsidy_five_a' => "a) Total value of lease charge of the land ",
        'ce_grant_of_subsidy_five_b' => "b) Total cost of development of land",
        'ce_grant_of_subsidy_six' => "6. Name of agency executing development of land",
        'ce_grant_of_subsidy_seven' => "7. Amount already paid(to be supported by APR).",
        'ce_grant_of_subsidy_eight' => "8. Subsidy already received ",
        'ce_grant_of_subsidy_nine' => "9. Present claim amount",
        'ce_grant_of_subsidy_ten_a' => "(a) Technical ",
        'ce_grant_of_subsidy_ten_b' => "(b) Non- Technical",
        'ce_grant_of_subsidy_eleven' => "11. Item of production ",
        'ce_grant_of_subsidy_twelve' => "12. Value of production during the last 1 year",


        // 10
        'commerce_subsidy_cost_transportation_one'=>"1. Name Of The Unit ",
        'commerce_subsidy_cost_transportation_two'=>"2. Address ",
        'commerce_subsidy_cost_transportation_two_a'=>"a)Office ",
        'commerce_subsidy_cost_transportation_two_b'=>"b) Factory ",
        'commerce_subsidy_cost_transportation_three'=>"3. Constitution Proprietorship / Partnership / Co- Operative Society / Private. Limited ",
        'commerce_subsidy_cost_transportation_four'=>"4. Name And Address Of The Proprietor/ Partner / Chairman / Director ",
        'commerce_subsidy_cost_transportation_five'=>"5. Regn. No. And Date Of The Unit ",
        'commerce_subsidy_cost_transportation_six'=>"6. Date Of Commencement Of Production / Taking Effective Steps. ",
        'commerce_subsidy_cost_transportation_seven'=>"7. Items Of Manufacture/ To Be Manufacture ",
        'commerce_subsidy_cost_transportation_eight'=>"8. Investment (Existing/Proposed) ",
        'commerce_subsidy_cost_transportation_eight_a'=>" a) Land & Building ",
        'commerce_subsidy_cost_transportation_eight_b'=>"b) Plant & Machineries  ",
        'commerce_subsidy_cost_transportation_eight_c'=>"c) Others  ",
        'commerce_subsidy_cost_transportation_nine'=>"9. Employment (Existing/ Proposed) ",
        'commerce_subsidy_cost_transportation_nine_a'=>" a) Technical ",
        'commerce_subsidy_cost_transportation_nine_b'=>"b) Non-Technical  ",
        'commerce_subsidy_cost_transportation_ten'=>"10. Particulars of Plants & Machineries Transported (Annexure-I) ",
        'commerce_subsidy_cost_transportation_ten_a'=>"a) Quantity/ Weight ",
        'commerce_subsidy_cost_transportation_ten_b'=>"b) Values ",
        'commerce_subsidy_cost_transportation_ten_c'=>"c) Transportation charge (To be supported by original voucher) ",
        'commerce_subsidy_cost_transportation_eleven'=>"11. Amount of Subsidy claimed with Percentage. ",


    ];
}
