<?php

namespace App\Utils;

class KeysUtil
{
    const APPLICATIONS = [
        'C&E_ALLOTMENT_PLOT' => [

            'applicant_name',
            'industrial_location_name',

            'communication_address',
            'communication_street',
            'communication_city',
            'communication_pin_no',
            'communication_house_no',
            'communication_office_phn',
            'communication_residence_phn',
            'communication_mobile_phn',
            'communication_email',
            'communication_website',
            'communication_district',

            'proposed_or_existing',

            'proposed_street',
            'proposed_city',

            'proposed_house_no',
            'proposed_office_phn',
            'proposed_residence_phn',
            'proposed_mobile_phn',

            'enterprise_name',
            'enterprise_category',
            'nature_activity',
            'incase_others',
            'isAncillary',
            'if_yes',
            'organization_type',
            'product_manufacture',
            'service_provided',
            'proposed_investment',
            'installed_capacity',
            'area_plot',
            'no_of_ready_build',
            'electric_power',
            'daily_water',

            // 'applicant_signature: ',
            // 'reg_certificate',
            // 'voters_id'

        ],
        'C&E_POWER_GENERATING' => [
            'commerce_power_generating_one',
            'commerce_power_generating_two',
            'commerce_power_generating_two_a',
            'commerce_power_generating_two_b',
            'commerce_power_generating_three',
            'commerce_power_generating_four',
            'commerce_power_generating_five',
            'commerce_power_generating_six',
            'commerce_power_generating_seven',
            'commerce_power_generating_eight',
            'commerce_power_generating_nine',
            'commerce_power_generating_ten',
            'commerce_power_generating_eleven',
            'commerce_power_generating_twelve',
            'commerce_power_generating_thirteen',
            'commerce_power_generating_fourteen',
            'commerce_power_generating_fifteen',
            'commerce_power_generating_sixteen',
        ],

        'C&E_COST_PROJECT' => [
            'commerce_cost_project_one',
            'commerce_cost_project_two',
            'commerce_cost_project_two_a',
            'commerce_cost_project_two_b',
            'commerce_cost_project_three',
            'commerce_cost_project_four',
            'commerce_cost_project_five',
            'commerce_cost_project_six',
            'commerce_cost_project_seven',
            'commerce_cost_project_eight',
            'commerce_cost_project_nine',
            'commerce_cost_project_ten',
            'commerce_cost_project_eleven',
            'commerce_cost_project_twelve',
        ],

        'C&E_INTEREST_SUBSIDY' => [
            "cne_interest_subsidy_one",
            "cne_interest_subsidy_oneA",
            "cne_interest_subsidy_oneB",
            "cne_interest_subsidy_oneB1",
            "cne_interest_subsidy_oneB2",
            "cne_interest_subsidy_oneC",
            "cne_interest_subsidy_oneC1",
            "cne_interest_subsidy_oneC2",
            "cne_interest_subsidy_oneD",
            "cne_interest_subsidy_oneD1",
            "cne_interest_subsidy_oneD2",
            "cne_interest_subsidy_two",
            "cne_interest_subsidy_twoA",
            "cne_interest_subsidy_towA1",
            "cne_interest_subsidy_twoA2",
            "cne_interest_subsidy_twoB",
            "cne_interest_subsidy_three",
            "cne_interest_subsidy_threeA",
            "cne_interest_subsidy_threeB",
            "cne_interest_subsidy_four",
            "cne_interest_subsidy_fourA",
            "cne_interest_subsidy_fourB",
            "cne_interest_subsidy_five",
            "cne_interest_subsidy_fiveA",
            "cne_interest_subsidy_fiveA1",
            "cne_interest_subsidy_fiveA2",
            "cne_interest_subsidy_fiveB",
            "cne_interest_subsidy_fiveB1",
            "cne_interest_subsidy_fiveB2",
            "cne_interest_subsidy_fiveC",
            "cne_interest_subsidy_fiveC1",
            "cne_interest_subsidy_fiveC2",
            "cne_interest_subsidy_fiveD",
            "cne_interest_subsidy_six",
            "cne_interest_subsidy_seven",
            "cne_interest_subsidy_seven1",
            "cne_interest_subsidy_seven2",
            "cne_interest_subsidy_eight",
            "cne_interest_subsidy_eightA",
            "cne_interest_subsidy_eightA1",
            "cne_interest_subsidy_eightA2",
            "cne_interest_subsidy_eightB",
            "cne_interest_subsidy_eightBTitle",
            "cne_interest_subsidy_eightBTitle1",
            "cne_interest_subsidy_eightBTitl11",
            "cne_interest_subsidy_eightBTitl12",
            "cne_interest_subsidy_eightBTitle2",
            "cne_interest_subsidy_eightBTitle21",
            "cne_interest_subsidy_eightBTitle22",
            "cne_interest_subsidy_nine",
            "cne_interest_subsidy_nineA",
            "cne_interest_subsidy_nineAnewUnit",
            "cne_interest_subsidy_nineAexist",
            "cne_interest_subsidy_nineAexist1",
            "cne_interest_subsidy_nineAexist2",
            "cne_interest_subsidy_nineB",
            "cne_interest_subsidy_nineB1",
            "cne_interest_subsidy_nineB1newUnit",
            "cne_interest_subsidy_nineB1exist",
            "cne_interest_subsidy_nineB1exist1",
            "cne_interest_subsidy_nineB1exist2",
            "cne_interest_subsidy_nineB2",
            "cne_interest_subsidy_nineB2newUnit",
            "cne_interest_subsidy_nineB2exist",
            "cne_interest_subsidy_nineB2exist1",
            "cne_interest_subsidy_nineB2exist2",
            "cne_interest_subsidy_nineC",
            "cne_interest_subsidy_nineCnewUnit",
            "cne_interest_subsidy_nineCexist",
            "cne_interest_subsidy_nineCexist1",
            "cne_interest_subsidy_nineCexist2",
            "cne_interest_subsidy_nineD",
            "cne_interest_subsidy_nineDnewUnit",
            "cne_interest_subsidy_nineDexist",
            "cne_interest_subsidy_nineDexist1",
            "cne_interest_subsidy_nineDexist2",
            "cne_interest_subsidy_nineE",
            "cne_interest_subsidy_nineEnewUnit",
            "cne_interest_subsidy_nineEexist",
            "cne_interest_subsidy_nineEexist1",
            "cne_interest_subsidy_nineEexist2",
            "cne_interest_subsidy_nineF",
            "cne_interest_subsidy_nineFnewUnit",
            "cne_interest_subsidy_nineFexist",
            "cne_interest_subsidy_nineFexist1",
            "cne_interest_subsidy_nineFexist2",
            "cne_interest_subsidy_total",
            "cne_interest_subsidy_totalnewUnit",
            "cne_interest_subsidy_totalexist",
            "cne_interest_subsidy_totalexist1",
            "cne_interest_subsidy_totalexist2",
            "cne_interest_subsidy_ten",
            "cne_interest_subsidy_eleven",
            "cne_interest_subsidy_elevenA",
            "cne_interest_subsidy_elevenA1",
            "cne_interest_subsidy_elevenB",
            "cne_interest_subsidy_elevenB1",
            "cne_interest_subsidy_elevenB2",
            "cne_interest_subsidy_twelve",
            "cne_interest_subsidy_twelveA",
            "cne_interest_subsidy_twelveB",
            "cne_interest_subsidy_thirteen",
            "cne_interest_subsidy_thirteenA",
            "cne_interest_subsidy_thirteenB",
            "cne_interest_subsidy_thirteenC",
            "cne_interest_subsidy_thirteenC1",
            "cne_interest_subsidy_thirteenC2",
            "cne_interest_subsidy_fourteen",
            "cne_interest_subsidy_fifteen",
        ],

        'POWER_NEW_CONNECTION' => [
            "power_new_connection_applicant_name",
            "power_new_connection_father_name",
            "power_new_connection_communication_address",
            "power_new_connection_communication_house",
            "power_new_connection_communication_street",
            "power_new_connection_communication_area",
            "power_new_connection_communication_district",
            "power_new_connection_connection_address",
            "power_new_connection_connection_house",
            "power_new_connection_connection_street",
            "power_new_connection_connection_area",
            "power_new_connection_connection_district",
            "power_new_connection_supply_category",
            "power_new_connection_supply_purpose",
            "power_new_connection_total_load",
            "power_new_connection_supply_type",
            "power_new_connection_is_temporary",
            "power_new_connection_temporay_from",
            "power_new_connection_temporay_to",
            "power_new_connection_is_laying_service",
            "power_new_connection_own_meter",
            // "power_new_connection_applicant_type",
            // "power_new_connection_photo",
            "power_new_connection_for",
            // "power_new_connection_identity_proof"
        ],

        'FIRE_NOC' => [
            "fire_one",
            "fire_one_a",
            "fire_one_b",
            "fire_two",
            "fire_two_a",
            "fire_two_b",
            "fire_three",
            "fire_four",
            "fire_five",
            "fire_six",
            "fire_seven",
            "fire_eight",
            "fire_nine",
            "fire_ten",
            "fire_eleven",
            "fire_twelve",
            "fire_thirteen",
            "fire_fourteen",
            "fire_fifteen",
            "fire_sixteen",
            "fire_seventeen",
            "fire_eighteen",
            "fire_tick_any",
            "fire_nineteen",
            "fire_nineteen_a",
            "fire_nineteen_b",
            "fire_nineteen_c",
            "fire_twenty",
            "fire_twenty_a",
            "fire_twenty_b",
            "fire_twentyone",
            "fire_twentytwo",
            "fire_twentythree",
            "fire_twentyfour",
            "fire_twentyfive",
            "fire_twentysix"
        ],

        'PWD_ROAD_CUTTING' => [
            "pwd_road_cutting_one",
            "pwd_road_cutting_two",
            "pwd_road_cutting_two_a",
            "pwd_road_cutting_two_b",
            "pwd_road_cutting_two_c",
            "pwd_road_cutting_three",
            "pwd_road_cutting_three_a",
            "pwd_road_cutting_three_b",
            "pwd_road_cutting_three_c",
            "pwd_road_cutting_three_d",
            "pwd_road_cutting_four",
            "pwd_road_cutting_four_a",
            "pwd_road_cutting_four_b",
            "pwd_road_cutting_four_c",
            "pwd_road_cutting_four_d",
            "pwd_road_cutting_five",
            "pwd_road_cutting_six",
        ],
        'PHE_WATER_CONNECTION' => [
            'phe_water_connection_one',
            'phe_water_connection_two',
            'phe_water_connection_three',
            'phe_water_connection_four',
            'phe_water_connection_five',
            'phe_water_connection_five_a',
            'phe_water_connection_five_b',
            'phe_water_connection_five_c',
            'phe_water_connection_five_d',
            'phe_water_connection_five_e',
            'phe_water_connection_five_f',
            'phe_water_connection_five_g',
            'phe_water_connection_six',
            'phe_water_connection_seven',
            'phe_water_connection_eight',
            'phe_water_connection_nine',
            'phe_water_connection_ten',
            'phe_water_connection_eleven',
            'phe_water_connection_twelve',
            'phe_water_connection_thirteen',
            'phe_water_connection_fourteen',
            'phe_water_connection_fourteen_a',
            'phe_water_connection_fourteen_b',
            // 'phe_water_connection_fifteen',
        ],
        'LAND_REVENUE_LAND_HOUSE' => [
            'land_revenue_land_house_one',
            'land_revenue_land_house_two',
            'land_revenue_land_house_two_a',
            'land_revenue_land_house_two_b',
            'land_revenue_land_house_two_c',
            'land_revenue_land_house_two_d',
            'land_revenue_land_house_three',
            'land_revenue_land_house_four',
            'land_revenue_land_house_five',
            'land_revenue_land_house_five_a',
            'land_revenue_land_house_five_b',
            'land_revenue_land_house_six',
            'land_revenue_land_house_seven',
            'land_revenue_land_house_eight',
            'land_revenue_land_house_eight_a',
            'land_revenue_land_house_eight_b',
            'land_revenue_land_house_nine',
            'land_revenue_land_house_ten',
            'land_revenue_land_house_ten_a',
            'land_revenue_land_house_ten_b',
            'land_revenue_land_house_ten_c',
            'land_revenue_land_house_ten_d',
            'land_revenue_land_house_eleven',
            'land_revenue_land_house_twelve',
            'land_revenue_land_house_thirteen',
            'land_revenue_land_house_thirteen_a',
            'land_revenue_land_house_thirteen_b',
        ],
        'LAND_REVENUE_LAND_SHOP' => [
            'land_revenue_land_house_one',
            'land_revenue_land_house_two',
            'land_revenue_land_house_two_a',
            'land_revenue_land_house_two_b',
            'land_revenue_land_house_two_c',
            'land_revenue_land_house_two_d',
            'land_revenue_land_house_three',
            'land_revenue_land_house_four',
            'land_revenue_land_house_five',
            'land_revenue_land_house_five_a',
            'land_revenue_land_house_five_b',
            'land_revenue_land_house_six',
            'land_revenue_land_house_seven',
            'land_revenue_land_house_eight',
            'land_revenue_land_house_eight_a',
            'land_revenue_land_house_eight_b',
            'land_revenue_land_house_nine',
            'land_revenue_land_house_ten',
            'land_revenue_land_house_ten_a',
            'land_revenue_land_house_ten_b',
            'land_revenue_land_house_ten_c',
            'land_revenue_land_house_ten_d',
            'land_revenue_land_house_eleven',
            'land_revenue_land_house_twelve',
            'land_revenue_land_house_thirteen',
            'land_revenue_land_house_thirteen_a',
            'land_revenue_land_house_thirteen_b',
        ],
        'LAND_REVENUE_LAND_SETTLEMENT' => [
            'land_revenue_land_settlement_one',
            'land_revenue_land_settlement_two',
            'land_revenue_land_settlement_two_a',
            'land_revenue_land_settlement_two_b',
            'land_revenue_land_settlement_two_c',
            'land_revenue_land_settlement_two_d',
            'land_revenue_land_settlement_three',
            'land_revenue_land_settlement_four',
            'land_revenue_land_settlement_five',
            'land_revenue_land_settlement_six',
            'land_revenue_land_settlement_six_a',
            'land_revenue_land_settlement_six_b',
            'land_revenue_land_settlement_seven',
            'land_revenue_land_settlement_eight',
            'land_revenue_land_settlement_nine',
            'land_revenue_land_settlement_ten',
            'land_revenue_land_settlement_eleven',
            'land_revenue_land_settlement_twelve',
            'land_revenue_land_settlement_twelve_a',
            'land_revenue_land_settlement_twelve_b',
            'land_revenue_land_settlement_twelve_c',
            'land_revenue_land_settlement_twelve_d',
            'land_revenue_land_settlement_thirteen',
            'land_revenue_land_settlement_fourteen',
            'land_revenue_land_settlement_fifteen',
            'land_revenue_land_settlement_fifteen_a',
            'land_revenue_land_settlement_fifteen_b',
            'land_revenue_land_settlement_sixteen',
            'land_revenue_land_settlement_sixteen_a',
            'land_revenue_land_settlement_sixteen_b',
        ],
        'LAND_REVENUE_LAND_DIVERSION' => [
            'land_revenue_land_diversion_one',
            'land_revenue_land_diversion_two',
            'land_revenue_land_diversion_three',
            'land_revenue_land_diversion_four',
            'land_revenue_land_diversion_five',
            'land_revenue_land_diversion_five_a',
            'land_revenue_land_diversion_five_b',
            'land_revenue_land_diversion_six',
            'land_revenue_land_diversion_seven',
            'land_revenue_land_diversion_eight',
            'land_revenue_land_diversion_nine',
            'land_revenue_land_diversion_ten',
            'land_revenue_land_diversion_eleven'
        ],
        'LAND_REVENUE_LAND_TRANSFER' => [],

        'POLLUTION_ACCIDENT_MEDICAL' => [
            'pollution_accident_medical_one',
            'pollution_accident_medical_one_a',
            'pollution_accident_medical_one_b',
            'pollution_accident_medical_two',
            'pollution_accident_medical_three',
            'pollution_accident_medical_four',
            'pollution_accident_medical_five',
            'pollution_accident_medical_six',
            'pollution_accident_medical_seven',
            'pollution_accident_medical_eight',
            'pollution_accident_medical_nine',
            'pollution_accident_medical_ten',
            'pollution_accident_medical_designation',
        ],
        'POLLUTION_ACCIDENT_HAZARDOUS' => [
            'pollution_accident_medical_one',
            'pollution_accident_medical_one_a',
            'pollution_accident_medical_one_b',
            'pollution_accident_medical_two',
            'pollution_accident_medical_three',
            'pollution_accident_medical_four',
            'pollution_accident_medical_five',
            'pollution_accident_medical_six',
            'pollution_accident_medical_seven',
            'pollution_accident_medical_eight',
            'pollution_accident_medical_nine',
            'pollution_accident_medical_ten',
            'pollution_accident_medical_designation',
        ],
        'POLLUTION_ACCIDENT_SOLIDWASTE' => [
            'pollution_accident_medical_one',
            'pollution_accident_medical_one_a',
            'pollution_accident_medical_one_b',
            'pollution_accident_medical_two',
            'pollution_accident_medical_three',
            'pollution_accident_medical_four',
            'pollution_accident_medical_five',
            'pollution_accident_medical_six',
            'pollution_accident_medical_seven',
            'pollution_accident_medical_eight',
            'pollution_accident_medical_nine',
            'pollution_accident_medical_ten',
            'pollution_accident_medical_designation',
        ],
        'FOOD_DRUG_GENERAL_RETAIL' => [
            'food_drug_general_one',
            'food_drug_general_one_i_we',
            'food_drug_general_one_apply_for',
            'food_drug_general_one_situated_at',
            'food_drug_general_two',
            'food_drug_general_two_i',
            'food_drug_general_two_ii',
            'food_drug_general_three',
            'food_drug_general_four',
            'food_drug_general_five',
            // 'food_drug_general_five_i',
            'food_drug_general_five_ii',
            'food_drug_general_five_iii',
            'food_drug_general_five_iv',
            'food_drug_general_addl',
            'food_drug_general_addl_one',
            'food_drug_general_addl_one_i',
            'food_drug_general_addl_one_ii',
            'food_drug_general_addl_one_iii',
            'food_drug_general_addl_one_iv',
            'food_drug_general_addl_one_v',
            'food_drug_general_addl_one_vi',
            'food_drug_general_addl_two',
            'food_drug_general_addl_exp',
            'food_drug_general_addl_exp_i',
            'food_drug_general_addl_exp_ii',
            'food_drug_general_addl_three',
            'food_drug_general_addl_three_i',
            'food_drug_general_addl_three_ii',
            'food_drug_general_addl_three_iii',
            'food_drug_general_addl_three_iv',
            'food_drug_general_addl_four',
            'food_drug_general_addl_five',
            'food_drug_general_addl_six',
            'food_drug_general_addl_seven',
            'food_drug_general_addl_seven_i',
            'food_drug_general_addl_seven_ii',
            'food_drug_general_addl_seven_iii',
        ],
        'FOOD_DRUG_RESTRICTED_RETAIL' => [
            'food_drug_restricted_one',
            'food_drug_restricted_one_i_we',
            'food_drug_restricted_one_of',
            'food_drug_restricted_one_i',
            'food_drug_restricted_one_ii',
            'food_drug_restricted_two',
            'food_drug_restricted_three',
            'food_drug_restricted_four',
            'food_drug_restricted_five',
            'food_drug_restricted_five_i',
            'food_drug_restricted_five_ii',
            'food_drug_restricted_six',
            'food_drug_restricted_six_i',
            'food_drug_restricted_six_ii',
            'food_drug_restricted_six_iii',
            'food_drug_restricted_addl',
            'food_drug_restricted_addl_one',
            'food_drug_restricted_addl_one_i',
            'food_drug_restricted_addl_one_ii',
            'food_drug_restricted_addl_one_iii',
            'food_drug_restricted_addl_one_iv',
            'food_drug_restricted_addl_one_v',
            'food_drug_restricted_addl_two',
            'food_drug_restricted_addl_two_i',
            'food_drug_restricted_addl_exp',
            'food_drug_restricted_addl_exp_i',
            'food_drug_restricted_addl_exp_ii',
            'food_drug_restricted_addl_three',
            'food_drug_restricted_addl_four',
            'food_drug_restricted_addl_four_i',
            'food_drug_restricted_addl_four_ii',
            'food_drug_restricted_addl_four_iii',
            'food_drug_restricted_addl_four_iv',
            'food_drug_restricted_zau_zawng',
            'food_drug_restricted_zau_zawng_i',
            'food_drug_restricted_zau_zawng_ii',
            'food_drug_restricted_zau_zawng_iii',
            'food_drug_restricted_addl_five',
            'food_drug_restricted_addl_five_i',
            'food_drug_restricted_addl_five_ii',
            'food_drug_restricted_addl_six',
            'food_drug_restricted_addl_six_i',
            'food_drug_restricted_addl_six_ii',
        ]

    ];

    const LABELS = [

        // COMMERCE AND INSUSTRIES - ALLOTMENT PLOT
        'applicant_name' => 'Applicant Name',
        'industrial_location_name' => 'Name & Location of Industrial Area',
        'communication_address' => 'Address for Communications',
        'communication_street' => 'Steet',
        'communication_city' => 'City/Town/Village',
        'communication_pin_no' => 'PIN No',
        'communication_house_no' => 'House No',
        'communication_office_phn' => 'Office Phone Number',
        'communication_residence_phn' => 'Residense Phone Number',
        'communication_mobile_phn' => 'Mobile Phone',
        'communication_email' => 'Email Address',
        'communication_website' => 'Website',
        'communication_district' => 'District',
        'proposed_or_existing' => 'Whether Proposed Or Existing Unit If Existing, Detail Address Of The Unit: Proposed/Existing.',
        'proposed_street' => 'street',
        'proposed_city' => 'city',
        'proposed_house_no' => 'House No',
        'proposed_office_phn' => 'Office No',
        'proposed_residence_phn' => 'Residence No',
        'proposed_mobile_phn' => 'Mobile No',
        'enterprise_name' => 'Name of the Enterprise',
        'enterprise_category' => 'Category Of Enterprise ',
        'nature_activity' => 'Nature Of Activity',
        'incase_others' => 'Whether The Unit Is Ancillary',
        'isAncillary' => 'Incase Of Others, Please Specify',
        'if_yes' => 'If Yes, Give Detail',
        'organization_type' => 'Type Of Organization',
        'product_manufacture' => 'Product To Be Manufacture ',
        'service_provided' => 'Service To Be Provided',
        'proposed_investment' => 'Proposed Investment In Fixed Assets (Rs. In Lakhs)',
        'installed_capacity' => 'Installed Capacity',
        'area_plot' => 'Area In Plot Required',
        'no_of_ready_build' => 'No. Of Ready Build Shed Required ',
        'electric_power' => 'Requirement Of Electric Power',
        'daily_water' => 'Daily Requirement Of Water',

        // COMMERCE AND INSUSTRIES - POWER GENERATING
        'commerce_power_generating_one' => '1. Name Of The Unit',
        'commerce_power_generating_two' => '2. Address',
        'commerce_power_generating_two_a' => 'a)Office',
        'commerce_power_generating_two_b' => 'b) Factory',
        'commerce_power_generating_three' => '3. Constitution Proprietorship / Partnership / Co- Operative Society / Private. Limited',
        'commerce_power_generating_four' => '4. Name And Address Of The Proprietor/Partner/Chairman/Director',
        'commerce_power_generating_five' => '5. Regn. No. And Date Of The Unit',
        'commerce_power_generating_six' => '6. Date Of Commencement Of Production / Taking Effective Steps',
        'commerce_power_generating_seven' => '7. Items Of Manufacture/ To Be Manufacture',
        'commerce_power_generating_eight' => '8. Investment (Existing/Proposed)',
        'commerce_power_generating_nine' => '9. Employment (Existing/Proposed)',
        'commerce_power_generating_ten' => '10. Name/Brand of the Power Generating set with power output capacity',
        'commerce_power_generating_eleven' => '11. Name of Supplier with complete Address',
        'commerce_power_generating_twelve' => '12. Total requirement of power of the Unit (in term of P/K.W)',
        'commerce_power_generating_thirteen' => '13. Name of the executing the installation of the set',
        'commerce_power_generating_fourteen' => '14. Actual cost of the power generating se (to be supported by Original Voucher)',
        'commerce_power_generating_fifteen' => '15. Actual installation charge (to be supported by Original voucher)',
        'commerce_power_generating_sixteen' => '16. Amount of subsidy claimed with percentage',

        // COMMERCE AND INSUSTRIES -  COST OF PROJECT REPORT
        'commerce_cost_project_one' => '1. Name of the unit',
        'commerce_cost_project_two' => '2. Address',
        'commerce_cost_project_two_a' => 'a) Office',
        'commerce_cost_project_two_b' => 'b) Factory',
        'commerce_cost_project_three' => '3. Constitution Proprietorship/Partnership/Co- Operative Society/ Private. Limited',
        'commerce_cost_project_four' => '4. Name and Address of the Proprietor/Partner /Director',
        'commerce_cost_project_five' => '5. Registration/License No. of the Unit',
        'commerce_cost_project_six' => '6. Date of commencement of Production/effective steps',
        'commerce_cost_project_seven' => '7. Items of manufacture/ to be manufacture',
        'commerce_cost_project_eight' => '8. Investment (Existing/ Proposed)',
        'commerce_cost_project_nine' => '9. Employment (Existing/ Proposed)',
        'commerce_cost_project_ten' => '10. Cost of Project Report (to be supported by original voucher',
        'commerce_cost_project_eleven' => '11. Name & Address of consultant/Agency',
        'commerce_cost_project_twelve' => '12. Amount of subsidy claimed with percentage',


        // COMMERCE AND INSUSTRIES - INTEREST SUBSIDY
        "cne_interest_subsidy_one" => "1.",
        "cne_interest_subsidy_oneA" => "A) Name Of The Unit",
        "cne_interest_subsidy_oneB" => "B) Office Address With Telephone / Mobile No. )",
        "cne_interest_subsidy_oneB1" => "1) Office Address",
        "cne_interest_subsidy_oneB2" => "2. Mobile Number",
        "cne_interest_subsidy_oneC" => "C) Factory Address With Telephone No.",
        "cne_interest_subsidy_oneC1" => "1) Factory Address",
        "cne_interest_subsidy_oneC2" => "2. Telephone No.",
        "cne_interest_subsidy_oneD" => "D) Indicate The Claim No ( Say 1st Claim, 2nd Claim Etc)",
        "cne_interest_subsidy_oneD1" => "1) Factory Address",
        "cne_interest_subsidy_oneD2" => "2. Telephone No.",
        "cne_interest_subsidy_two" => "2",
        "cne_interest_subsidy_twoA" => "A)Registration Number Under NEIIPP, 2007 Along With Date)",
        "cne_interest_subsidy_towA1" => "1) Registration Number",
        "cne_interest_subsidy_twoA2" => "2. Date",
        "cne_interest_subsidy_twoB" => "B) Any Other Registration Number Required Statutorily/mandatorily",
        "cne_interest_subsidy_three" => "3. Constitution Of The Unit Alongwith Date (Proprietorship / Partnership / Private Limited / Limited Company / Cooperative Society )",
        "cne_interest_subsidy_threeA" => "A) Constitution Of The Unit",
        "cne_interest_subsidy_threeB" => "B) Date",
        "cne_interest_subsidy_four" => "4. Name/s , Address(es) Of The Proprietor/ Partners / Directors Of Board Of Directors / Secretary And President (as Applicable)",
        "cne_interest_subsidy_fourA" => "A) Name",
        "cne_interest_subsidy_fourB" => "B) Address",
        "cne_interest_subsidy_five" => "5. Details Of Enterprise Registration",
        "cne_interest_subsidy_fiveA" => "A) Acknowledgement Of Entrepreneur Memorandum(EM) Part-I, No & Date",
        "cne_interest_subsidy_fiveA1" => "1) Acknowledgement EM Number",
        "cne_interest_subsidy_fiveA2" => "2. Date",
        "cne_interest_subsidy_fiveB" => "B) Acknowledgement Of Entrepreneur Memorandum(EM) Part-II, No & Date",
        "cne_interest_subsidy_fiveB1" => "1) Acknowledgement EM Number",
        "cne_interest_subsidy_fiveB2" => "2. Date",
        "cne_interest_subsidy_fiveC" => "C) Acknowledgement Of Industrial Entrepreneur Memorandum (IEM) No & Date",
        "cne_interest_subsidy_fiveC1" => "1) Acknowledgement EM Number",
        "cne_interest_subsidy_fiveC2" => "2. Date",
        "cne_interest_subsidy_fiveD" => "D) Permanent Registration No In Case Of Existing Unit",
        "cne_interest_subsidy_six" => "6. Certificate Of The Unit Having Become Functional/operational (for Service Sector From Concerned Department)",
        "cne_interest_subsidy_seven" => "7.",
        "cne_interest_subsidy_seven1" => "1) Name Of The Product (for Manufacturing Sector )",
        "cne_interest_subsidy_seven2" => "2. Name Of The Activity (for Service Sector)",
        "cne_interest_subsidy_eight" => "8. Whether The Unit Is New Or An Existing Unit Under Going Substantial Expansion",
        "cne_interest_subsidy_eightA" => "A) In Case Of New Unit",
        "cne_interest_subsidy_eightA1" => "1) Date Of Commencement Of Production (Manufacturing Sector Units) ",
        "cne_interest_subsidy_eightA2" => "2. Date Of Becoming Operational (Service Sector Units)",
        "cne_interest_subsidy_eightB" => "B) In Case Of Existing Unit",
        "cne_interest_subsidy_eightBTitle" => "Date Of Going Into Commercial Production/becoming Operational",
        "cne_interest_subsidy_eightBTitle1" => "1) For Manufacturing Sector Units",
        "cne_interest_subsidy_eightBTitl11" => "1) Prior To Expansion ",
        "cne_interest_subsidy_eightBTitl12" => "2. After Expansion",
        "cne_interest_subsidy_eightBTitle2" => "2) For Service Sector Units",
        "cne_interest_subsidy_eightBTitle21" => "1) Prior To Expansion",
        "cne_interest_subsidy_eightBTitle22" => "2. After Expansion",
        "cne_interest_subsidy_nine" => "9. Capital Investment [to Be Supported By CA Certificate As Per Form-1D(A)(i)/Form:1D(A)(ii)] For Existing Unit",
        "cne_interest_subsidy_nineA" => "A) Land & Site Development",
        "cne_interest_subsidy_nineAnewUnit" => "For New Unit (Amount In Rs.)",
        "cne_interest_subsidy_nineAexist" => "For Existing Unit Undergoing Expansion (Amount In Rs.)",
        "cne_interest_subsidy_nineAexist1" => "1) Prior To Expansion",
        "cne_interest_subsidy_nineAexist2" => "2. After Expansion",
        "cne_interest_subsidy_nineB" => "B) Building",
        "cne_interest_subsidy_nineB1" => "1) Office Building",
        "cne_interest_subsidy_nineB1newUnit" => "For New Unit (Amount In Rs.)",
        "cne_interest_subsidy_nineB1exist" => "For Existing Unit Undergoing Expansion (Amount In Rs.)",
        "cne_interest_subsidy_nineB1exist1" => "1) Prior To Expansion",
        "cne_interest_subsidy_nineB1exist2" => "2. After Expansion",
        "cne_interest_subsidy_nineB2" => "2) Factory Building",
        "cne_interest_subsidy_nineB2newUnit" => "For New Unit (Amount In Rs.)",
        "cne_interest_subsidy_nineB2exist" => "For Existing Unit Undergoing Expansion (Amount In Rs.)",
        "cne_interest_subsidy_nineB2exist1" => "1) Prior To Expansion",
        "cne_interest_subsidy_nineB2exist2" => "2. After Expansion",
        "cne_interest_subsidy_nineC" => "C) Plant And Machinery /components/essential Items",
        "cne_interest_subsidy_nineCnewUnit" => "For New Unit (Amount In Rs.)",
        "cne_interest_subsidy_nineCexist" => "For Existing Unit Undergoing Expansion (Amount In Rs.)",
        "cne_interest_subsidy_nineCexist1" => "1) Prior To Expansion",
        "cne_interest_subsidy_nineCexist2" => "2. After Expansion",
        "cne_interest_subsidy_nineD" => "D) Accessories",
        "cne_interest_subsidy_nineDnewUnit" => "For New Unit (Amount In Rs.)",
        "cne_interest_subsidy_nineDexist" => "For Existing Unit Undergoing Expansion (Amount In Rs.)",
        "cne_interest_subsidy_nineDexist1" => "1) Prior To Expansion",
        "cne_interest_subsidy_nineDexist2" => "2. After Expansion",
        "cne_interest_subsidy_nineE" => "E) Miscellaneous Fixed Assets",
        "cne_interest_subsidy_nineEnewUnit" => "For New Unit (Amount In Rs.)",
        "cne_interest_subsidy_nineEexist" => "For Existing Unit Undergoing Expansion (Amount In Rs.)",
        "cne_interest_subsidy_nineEexist1" => "1) Prior To Expansion",
        "cne_interest_subsidy_nineEexist2" => "2. After Expansion",
        "cne_interest_subsidy_nineF" => "F) Preliminary And Preoperative Expanses",
        "cne_interest_subsidy_nineFnewUnit" => "For New Unit (Amount In Rs.)",
        "cne_interest_subsidy_nineFexist" => "For Existing Unit Undergoing Expansion (Amount In Rs.)",
        "cne_interest_subsidy_nineFexist1" => "1) Prior To Expansion",
        "cne_interest_subsidy_nineFexist2" => "2. After Expansion",
        "cne_interest_subsidy_total" => "Total",
        "cne_interest_subsidy_totalnewUnit" => "For New Unit (Amount In Rs.)",
        "cne_interest_subsidy_totalexist" => "For Existing Unit Undergoing Expansion (Amount In Rs.)",
        "cne_interest_subsidy_totalexist1" => "1) Prior To Expansion",
        "cne_interest_subsidy_totalexist2" => "2. After Expansion",
        "cne_interest_subsidy_ten" => "10. Increase In Investment (in Case Of Existing Unit)",
        "cne_interest_subsidy_eleven" => "11",
        "cne_interest_subsidy_elevenA" => "A) Annual Turnover Of The Unit",
        "cne_interest_subsidy_elevenA1" => "1) For New Unit (in Rs.)",
        "cne_interest_subsidy_elevenB" => "B) For Existing Unit Undergoing Expansion",
        "cne_interest_subsidy_elevenB1" => "1) Annual Turnover Before Expansion (in Rs)",
        "cne_interest_subsidy_elevenB2" => "2) Annual Turnover After Expansion (in Rs.)",
        "cne_interest_subsidy_twelve" => "12",
        "cne_interest_subsidy_twelveA" => "A) Names Of The Raw Materials Utilized With Quantity And Value During The Claim Period.",
        "cne_interest_subsidy_twelveB" => "B) Name Of The Finished Product(s) Alongwith Quantity And Value During The Claim Period.",
        "cne_interest_subsidy_thirteen" => "13",
        "cne_interest_subsidy_thirteenA" => "A) Name Of The Bank Branch Providing Working Capital Loan",
        "cne_interest_subsidy_thirteenB" => "B) Maximum Limit Of Working Capital Sanctioned Along With Rate Of Interest",
        "cne_interest_subsidy_thirteenC" => "C) Sanction No. & Date",
        "cne_interest_subsidy_thirteenC1" => "1) Sanction No.",
        "cne_interest_subsidy_thirteenC2" => "2) Sanction Date",
        "cne_interest_subsidy_fourteen" => "14. Remarks, If Any.",
        "cne_interest_subsidy_fifteen" => "15. Employment Generation In Various Fields Of Work (Executive, Non-executive, Skilled, Un-skilled Etc.)",

        "power_new_connection_applicant_name" => "1.Name of the Applicant/Organization",
        "power_new_connection_father_name" => "2.Name of Father/ Husband/ Director/ Partner/ Trustee*",
        "power_new_connection_communication_address" => "Address for communication",
        "power_new_connection_communication_house" => "House/Plot/Premise No",
        "power_new_connection_communication_street" => "Street",
        "power_new_connection_communication_area" => "Area/Colony",
        "power_new_connection_communication_district" => "District",
        "power_new_connection_connection_address" => "Address of where the new connection is applied for/existing connection is required to be shifted",
        "power_new_connection_connection_house" => "House/Plot/Premise No",
        "power_new_connection_connection_street" => "Street",
        "power_new_connection_connection_area" => "Area/Colony",
        "power_new_connection_connection_district" => "District",
        "power_new_connection_supply_category" => "4.Category of Supply",
        "power_new_connection_supply_purpose" => "5.Purpose of Supply",
        "power_new_connection_total_load" => "6.Total Contracted Load applied for (in kW)",
        "power_new_connection_supply_type" => "7.Type of Supply",
        "power_new_connection_is_temporary" => "8.If Temporary supply, specify period of requirement",
        "power_new_connection_temporay_from" => "From (date)",
        "power_new_connection_temporay_to" => "To (date)",
        "power_new_connection_is_laying_service" => "9.Please indicate whether you want to carry out the works of laying service line and/or dedicated distribution facility for the electricity supply requisitioned.",
        "power_new_connection_own_meter" => "10.Please indicate whether you want to install your own CEA approved meter. (Yes/No)",
        // "power_new_connection_applicant_type" => "Applicant is",
        "power_new_connection_for" => "Applicant is",

        //Fire NOC
        "fire_one" => "1.Name And Address Of The Firm/company",
        "fire_one_a" => "(a)Name",
        "fire_one_b" => "(b)Address",
        "fire_two" => "2.Name And Contact Number Of Owner",
        "fire_two_a" => "(a)Name",
        "fire_two_b" => "(b)Contact Number",
        "fire_three" => "3.Location Of Building And Type Of Construction",
        "fire_four" => "4.Type Of Business",
        "fire_five" => "5.Plot Area",
        "fire_six" => "6.Covered Area",
        "fire_seven" => "7.Height Of Building",
        "fire_eight" => "8.No. Of Floors/storeys",
        "fire_nine" => "9.Total covered area of the building",
        "fire_ten" => "10.Expected no of occupants",
        "fire_eleven" => "11.Mode and type of production/type of occupancy",
        "fire_twelve" => "12.Electrical wiring system and sanctioned electrical load",
        "fire_thirteen" => "13.List of raw material(applicable for commercial/business enterprise)",
        "fire_fourteen" => "14.Name of finished products(applicable for commercial/business enterprise)",
        "fire_fifteen" => "15.Detail of insurance, if any",
        "fire_sixteen" => "16.Distance from nearest Fire Station(approx)",
        "fire_seventeen" => "17.Whether fresh NOC or Renewal",
        "fire_eighteen" => "18. Details of First Aid Fire Fighting equipment/extinguishers already installed within the premises",
        "fire_tick_any" => "Fixed Fire Fighting Installation (Tick for whatever is installed with numbers)",
        "fire_nineteen" => "19 Water supply",
        "fire_nineteen_a" => "(a) Under Ground Static Water Storage Tank with capacity",
        "fire_nineteen_b" => "(b) Terrace Tank with capacity",
        "fire_nineteen_c" => "(c) Water source",
        "fire_twenty" => "20 Pump capacity in LPM",
        "fire_twenty_a" => "a) Pump House at Ground level",
        "fire_twenty_b" => "a) Pump House at Ground level",
        "fire_twentyone" => "21 Detail of safety equipments, if Suits, Entry Suit , B.A. Set etc",
        "fire_twentytwo" => "22 Whether the workers / other staff are well conversant with the operation of first aid fire fighting equipments installed in the premises.",
        "fire_twentythree" => "23 Detail of flammable and hazardous materials alongwith Types and Quantity",
        "fire_twentyfour" => "24 Whether P. A system is installed",
        "fire_twentyfive" => "25 Compliance/ recommendation, if any, made in previous inspection",
        "fire_twentysix" => "26 Other information",

        //PWD Road Cutting
        "pwd_road_cutting_one" => "1. Name of applicant (in block letter)",
        "pwd_road_cutting_two" => "2. Contact address",
        "pwd_road_cutting_two_a" => "a) Landline No",
        "pwd_road_cutting_two_b" => "b) Mobile No",
        "pwd_road_cutting_two_c" => "c) Email identity",
        "pwd_road_cutting_three" => "3. Resident Address",
        "pwd_road_cutting_three_a" => "a) House No if any",
        "pwd_road_cutting_three_b" => "b) Locality/Veng",
        "pwd_road_cutting_three_c" => "c) City/Town/Village",
        "pwd_road_cutting_three_d" => "d) District",
        "pwd_road_cutting_four" => "4. Location of proposed land with respect to the road (specify landmark if any)",
        "pwd_road_cutting_four_a" => "a) House No if any",
        "pwd_road_cutting_four_b" => "b) Locality/Veng",
        "pwd_road_cutting_four_c" => "c) City/Town/Village",
        "pwd_road_cutting_four_d" => "d) District",
        "pwd_road_cutting_five" => "5. Land pass no (copy of pass shall be produced at the time of spot verification)",
        "pwd_road_cutting_six" => "6. Purpose of land applied for",

        //PHE New Water Connection
        'phe_water_connection_one' => "1. Applicant’s Name (Diltu hming)",
        'phe_water_connection_two' => "2. Father's Name (Pa hming)",
        'phe_water_connection_three' => "3. Occupation (Diltu hnathawh)",
        'phe_water_connection_four' => "4. Occupant (In luahtu)",
        'phe_water_connection_five' => "5. Address",
        'phe_water_connection_five_a' => "A). House No",
        'phe_water_connection_five_b' => "B) Locality (Veng)",
        'phe_water_connection_five_c' => "C) Street/lane",
        'phe_water_connection_five_d' => "D) City/Town",
        'phe_water_connection_five_e' => "E) Landmark",
        'phe_water_connection_five_f' => "F) Pin Code",
        'phe_water_connection_five_g' => "G) Phone no",
        'phe_water_connection_six' => "6. Email",
        'phe_water_connection_seven' => "7. Section",
        'phe_water_connection_eight' => "8. Connection Type",
        'phe_water_connection_nine' => "9. Category",
        'phe_water_connection_ten' => "10. Sub-Category",
        'phe_water_connection_eleven' => "11. No. of existing connection(s) (Dilna in-a connection awm tawh zat)",
        'phe_water_connection_twelve' => "12. No. of family (Dilna in-a chhungkaw cheng zat)",
        'phe_water_connection_thirteen' => "13. LSC/Land Pass/Relevant document (Attested Photocopy)",
        'phe_water_connection_fourteen' => "14. Pipe leh a zawmna bungrua",
        'phe_water_connection_fourteen_a' => "a)Department atanga lei",
        'phe_water_connection_fourteen_b' => "b)Mahni in tum",
        'phe_water_connection_fifteen' => "15.Signature Of The Applicant",

        //lAND REVENUE - LAND HOUSE & LAND SHOP/STALL

        'land_revenue_land_house_one' => '1.Name in capital (as appeared in EPIC or UID or PAN)',
        'land_revenue_land_house_two' => '2',
        'land_revenue_land_house_two_a' => '(a) Date Of Birth',
        'land_revenue_land_house_two_b' => '(b)Present Age',
        'land_revenue_land_house_two_c' => '(c) Place Of Birth',
        'land_revenue_land_house_two_d' => '(d)District',
        'land_revenue_land_house_three' => '3.Present Address',
        'land_revenue_land_house_four' => '4.Permanent Address',
        'land_revenue_land_house_five' => '5',
        'land_revenue_land_house_five_a' => '(a)Name Of Father',
        'land_revenue_land_house_five_b' => '(b)Name Of Mother',
        'land_revenue_land_house_six' => '6.Whether Applicant Belongs To A Tribal (Mizo) As Specified In Sub-section (45) Of Section 2 Of The Act',
        'land_revenue_land_house_seven' => '7.If Not Born In Mizoram, Do You Enclose Domicile Certificate Issued By Home Department?',
        'land_revenue_land_house_eight' => '8.Exact Location',
        'land_revenue_land_house_eight_a' => '(a)Area/Veng',
        'land_revenue_land_house_eight_b' => '(b) Indicate Category:Shop Or Stall',
        'land_revenue_land_house_nine' => '9.Name Of Village Council',
        'land_revenue_land_house_ten' => '10.Clearly Indicate Name(s) & Addresse(s) Of Immediate Neighbour',
        'land_revenue_land_house_ten_a' => '(a) South ( Chhim Lam )',
        'land_revenue_land_house_ten_b' => '(b) North ( Hmar Lam )',
        'land_revenue_land_house_ten_c' => '(c) West ( Khawthlang Lam )',
        'land_revenue_land_house_ten_d' => '(d) East ( Khawchhak Lam )',
        'land_revenue_land_house_eleven' => '11.Whether The Area Is Properly Cleared For Easy Movement Of Surveyors?',
        'land_revenue_land_house_twelve' => '12.Whether 4(four) Boundary Pillars As Prescribed By Revenue Department Are Provided For Fixing On The Day Of Survey Operation?',
        'land_revenue_land_house_thirteen' => '13.Other Contact Details',
        'land_revenue_land_house_thirteen_a' => '(a)Telephone Number',
        'land_revenue_land_house_thirteen_b' => '(b)Email ID',

        //lAND REVENUE - LAND SETTLEMENT

        'land_revenue_land_settlement_one' => '1.Name in capital (as appeared in EPIC or UID or PAN)',
        'land_revenue_land_settlement_two' => '2.',
        'land_revenue_land_settlement_two_a' => '(a) Date Of Birth',
        'land_revenue_land_settlement_two_b' => '(b)Present Age',
        'land_revenue_land_settlement_two_c' => '(c) Place Of Birth',
        'land_revenue_land_settlement_two_d' => '(d)District',
        'land_revenue_land_settlement_three' => '3.Whether Married?If Married,name Of Husband Or Wife(In Capital Letters)',
        'land_revenue_land_settlement_four' => '4.Present Address',
        'land_revenue_land_settlement_five' => '5.Permanent Address',
        'land_revenue_land_settlement_six' => '6.',
        'land_revenue_land_settlement_six_a' => '(a)Name Of Father',
        'land_revenue_land_settlement_six_b' => '(b)Name Of Mother',
        'land_revenue_land_settlement_seven' => '7.Whether Applicant Belongs To A Tribal (Mizo) As Specified In Sub-section (45) Of Section 2 Of The Act',
        'land_revenue_land_settlement_eight' => '8.If Not Born In Mizoram, Do You Enclose Domicile Certificate Issued By Home Department?',
        'land_revenue_land_settlement_nine' => '9.House Pass Number And Year',
        'land_revenue_land_settlement_ten' => '10.Exact Location/area/Veng',
        'land_revenue_land_settlement_eleven' => '11.Name Of Village Council',
        'land_revenue_land_settlement_twelve' => '12.Clearly Indicate Name(s) & Addresse(s) Of Immediate Neighbour',
        'land_revenue_land_settlement_twelve_a' => '(a) South ( Chhim Lam )',
        'land_revenue_land_settlement_twelve_b' => '(b) North ( Hmar Lam )',
        'land_revenue_land_settlement_twelve_c' => '(c) West ( Khawthlang Lam )',
        'land_revenue_land_settlement_twelve_d' => '(d) East ( Khawchhak Lam )',
        'land_revenue_land_settlement_thirteen' => '13.Whether The Area Is Properly Cleared For Easy Movement Of Surveyors?',
        'land_revenue_land_settlement_fourteen' => '14.Whether 6(six) Boundary Pillars As Prescribed By Revenue Department Are Provided For Fixing On The Day Of Survey Operation?',
        'land_revenue_land_settlement_fifteen' => '15.Checklist Whether The Following Documents Are Kept Ready For Inspection?',
        'land_revenue_land_settlement_fifteen_a' => '(a) House Pass Certificate',
        'land_revenue_land_settlement_fifteen_b' => '(b) Tax Clearance Certificate',
        'land_revenue_land_settlement_sixteen' => '16.Other Contact Details',
        'land_revenue_land_settlement_sixteen_a' => '(a)Telephone Number',
        'land_revenue_land_settlement_sixteen_b' => '(b)Email ID',

        //LAND REVENUE - LAND DIVERSION

        'land_revenue_land_diversion_one' => '1.Name of Applicant',
        'land_revenue_land_diversion_two' => "2.Father's Name",
        'land_revenue_land_diversion_three' => '3.Present Address',
        'land_revenue_land_diversion_four' => '4.Permanent Address',
        'land_revenue_land_diversion_five' => '5.',
        'land_revenue_land_diversion_five_a' => 'a)Registration No. with Year',
        'land_revenue_land_diversion_five_b' => 'b) Land holding No. with year',
        'land_revenue_land_diversion_six' => '6. Location of land as per Land Certificate',
        'land_revenue_land_diversion_seven' => '7. Area of land in Sq.metre',
        'land_revenue_land_diversion_eight' => '8. Purpose for which land was originally allotted',
        'land_revenue_land_diversion_nine' => '9. Ground on which diversion of land is applied ( separate sheet may be attached if needed)',
        'land_revenue_land_diversion_ten' => '10. Purpose for which use of land is to be diverted',
        'land_revenue_land_diversion_eleven' => '11. Whether up to date receipt of payment of land revenue & taxes are enclosed',

        //POLLUTION - ACCIDENT OF BIO-MEDICAL WASTES
        'pollution_accident_medical_one' => '1. Date And Time Of Accident',
        'pollution_accident_medical_one_a' => 'A) Date Of Accident',
        'pollution_accident_medical_one_b' => 'B) Time Of Accident',
        'pollution_accident_medical_two' => '2. Type Of Accident ',
        'pollution_accident_medical_three' => '3. Sequence Of Events Leading To Accident',
        'pollution_accident_medical_four' => '4. Has The Authority Been Informed Immediately',
        'pollution_accident_medical_five' => '5. The Type Of Waste Involved In Accident',
        'pollution_accident_medical_six' => '6. Assessment Of The Effects Of The Accidents On Human Health And The Environment',
        'pollution_accident_medical_seven' => '7. Emergency Measures Taken',
        'pollution_accident_medical_eight' => '8. Steps Taken To Alleviate The Effects Of Accidents',
        'pollution_accident_medical_nine' => '9. Steps taken to prevent the recurrence of such an accident',
        'pollution_accident_medical_ten' => '10. Does Your Facility Have An Emergency Control Policy? If Yes Give Details',
        'pollution_accident_medical_designation' => 'Designation',


        //FOOD AND DRUG - GENERAL RETAIL FORM19
        'food_drug_general_one' => "1.",
        'food_drug_general_one_i_we' => "I/We",
        'food_drug_general_one_apply_for' => "Hereby Apply For License To Sell By",
        'food_drug_general_one_situated_at' => "drugs specified in Schedules C and C(1) excluding those specified in Schedule X and/or drugs other than those specified in Schedules C,C(1) and X to the Drugs and Cosmetics Rules, 1945 and also to operate a pharmacy on the premises situated at",
        'food_drug_general_two' => "2. The Sale & Dispensing Of Drugs Will Be Made Under The Personal Supervision Of The Qualified Persons Namely:",
        'food_drug_general_two_i' => "I) Name",
        'food_drug_general_two_ii' => "II) Qualification",
        'food_drug_general_three' => "3. Categories Of Drugs To Be Sold",
        'food_drug_general_four' => "4. Particulars For Specified Storage Accommodation",
        'food_drug_general_five' => "5. A Fee Rs has been credited to the Government under the head of account 104 (1).",
        // 'food_drug_general_five_i' => "",
        'food_drug_general_five_ii' => "II) Name",
        'food_drug_general_five_iii' => "III) Full Address",
        'food_drug_general_five_iv' => "IV) Phone",
        'food_drug_general_addl' => "<span class='text-center'>ADDITIONAL INFORMATION TO BE FURNISHED BY THE APPLICANT</span> <hr>",
        'food_drug_general_addl_one' => "1.",
        'food_drug_general_addl_one_i' => "I) Hming",
        'food_drug_general_addl_one_ii' => "II) Kum",
        'food_drug_general_addl_one_iii' => "III) Pa Hming",
        'food_drug_general_addl_one_iv' => "IV) Address",
        'food_drug_general_addl_one_v' => "V) Telephone No",
        'food_drug_general_addl_one_vi' => 'VI) Eizawnna',
        'food_drug_general_addl_two' => "2.Educational QualificationEizawnna",
        'food_drug_general_addl_exp' => "Experience",
        'food_drug_general_addl_exp_i' => "I) Damdawi pangngai zawrh leh enkawl",
        'food_drug_general_addl_exp_ii' => "II) Homeo damdawi zawrh leh enkawl",
        'food_drug_general_addl_three' => "3. Pharmacist rawih tur hming",
        'food_drug_general_addl_three_i' => "I) Regn. No",
        'food_drug_general_addl_three_ii' => "II) Phone",
        'food_drug_general_addl_three_iii' => "III) Tuna thawh mek leh thawhna hmun",
        'food_drug_general_addl_three_iv' => "IV) Address",
        'food_drug_general_addl_four' => "4. Licence i dilna veng/khua",
        'food_drug_general_addl_five' => "5.Dawr tur chu mahni ta nge luah hawh tur?",
        'food_drug_general_addl_six' => "6.Eng ang building nge (Assam/Pucca)",
        'food_drug_general_addl_seven' => "7. A zau zawng",
        'food_drug_general_addl_seven_i' => "I) A dung ft",
        'food_drug_general_addl_seven_ii' => "II) A vang ft",
        'food_drug_general_addl_seven_iii' => "III) Area sq ft",





        //FOOD AND DRUG - RESTRICTED RETAIL FORM19A
        'food_drug_restricted_one' => "1.",
        'food_drug_restricted_one_i_we' => "I/We",
        'food_drug_restricted_one_of' => "Of",
        'food_drug_restricted_one_i' => "I) Drugs Other Than Those Specified In Schedules C, C (1) And X On The Premises Situated At",
        'food_drug_restricted_one_ii' => "II) Drugs Specified In [Schedule C (1)] On The Premises Situated At Or Drugs Specified In [Schedule C (1), As Vendor In The Area",
        'food_drug_restricted_two' => "2. Sales Shall Be Restricted To Such Drugs As Can Be Sold Without The Supervision Of A Qualified Person Under The Drugs & Cosmetics Rules.",
        'food_drug_restricted_three' => "3. Names Or Classes Of Drugs Proposed To Be Sold",
        'food_drug_restricted_four' => "4. Particulars Of The Storage Accommodation For The Storage Of [Schedule C (1)] Drugs On The Premises Referred To Above",
        'food_drug_restricted_five' => "5. The drugs for sale will be purchased from the following dealers and such other dealers as may be endorsed on the licence by Licencing Authority from time to time.",
        'food_drug_restricted_five_i' => "I) Name Of Dealers",
        'food_drug_restricted_five_ii' => "II) Lic. No",
        'food_drug_restricted_six' => "6. A Fee Rs ______ has been credited to the Government under the head of account 104 (1).        ",
        'food_drug_restricted_six_i' => "I) Name",
        'food_drug_restricted_six_ii' => "II) Full Address",
        'food_drug_restricted_six_iii' => "III) Phone",
        'food_drug_restricted_addl' => "<span class='text-center'>ADDITIONAL INFORMATION</span> <hr>",
        'food_drug_restricted_addl_one' => "1.",
        'food_drug_restricted_addl_one_i' => "I) Hming",
        'food_drug_restricted_addl_one_ii' => "II) Kum",
        'food_drug_restricted_addl_one_iii' => "III) Pa Hming",
        'food_drug_restricted_addl_one_iv' => "IV) Address",
        'food_drug_restricted_addl_one_v' => "V) Telephone No",
        'food_drug_restricted_addl_two' => "2.",
        'food_drug_restricted_addl_two_i' => "I) Educational Qualification",
        'food_drug_restricted_addl_exp' => "Experience",
        'food_drug_restricted_addl_exp_i' => "I) Damdawi Pangai Zawrh Leh Enkawl",
        'food_drug_restricted_addl_exp_ii' => "II) Homeo Damdawi Zawrh Leh Enkawl",
        'food_drug_restricted_addl_three' => "3. Tunah Eng Hna Nge I Thawh/enge I Tih Thin?",
        'food_drug_restricted_addl_four' => "4.",
        'food_drug_restricted_addl_four_i' => "I) Nangmah Ngeiin Drugs Store I Siamin I Enkawl Thei Dawn Em?",
        'food_drug_restricted_addl_four_ii' => "II) Chu Chu I Ta Nge I Luah Hawh Tur?",
        'food_drug_restricted_addl_four_iii' => "III) Tunah I Luah Tawh Nge I Hauh Mek?",
        'food_drug_restricted_addl_four_iv' => "IV) Eng Ang Building Nge (Assam/Pucca)",
        'food_drug_restricted_zau_zawng' => "A zau zawng",
        'food_drug_restricted_zau_zawng_i' => "I) A dung ft",
        'food_drug_restricted_zau_zawng_ii' => "II) A vang ft",
        'food_drug_restricted_zau_zawng_iii' => "III) Area sq ft",
        'food_drug_restricted_addl_five' => "5.",
        'food_drug_restricted_addl_five_i' => "I) Licence I Dilna Veng/khuaa Khawsa I Ni Em?",
        'food_drug_restricted_addl_five_ii' => "II) Khawsa I Nih Chuan Engtia Rei Nge I Awm Tawh?",
        'food_drug_restricted_addl_six' => "6.",
        'food_drug_restricted_addl_six_i' => "I) I Dilna Khuaa In Awm Zat? (Thingtlang A Chengte Tan)",
        'food_drug_restricted_addl_six_ii' => "II) Mihring Zat",

    ];

    public static function getApplicationKeys($applicationCode): array
    {
        return self::APPLICATIONS[$applicationCode];
    }

    public static function getApplicationLabel(string $key): string
    {
        return self::LABELS[$key];
    }
}
