<?php

namespace App\Utils;

class KeysUtil
{
    const APPLICATIONS = [
        'CODE1' => [

            'applicant_name',
            'industrial_location_name',


            'communication_address',
            'communication_street',
            'communication_city',
            'communication_pin_no',
            'communication_house_no',
            'communication_office_phn',
            'communication_residence_phn',
            'communication_mobile_phn',
            'communication_email',
            'communication_website',
            'communication_district',


            'proposed_or_existing',

            'proposed_street',
            'proposed_city',

            'proposed_house_no',
            'proposed_office_phn',
            'proposed_residence_phn',
            'proposed_mobile_phn',



            'enterprise_name',
            'enterprise_category',
            'nature_activity',
            'incase_others',
            'isAncillary',
            'if_yes',
            'organization_type',
            'product_manufacture',
            'service_provided',
            'proposed_investment',
            'installed_capacity',
            'area_plot',
            'no_of_ready_build',
            'electric_power',
            'daily_water',

            // 'applicant_signature: ',
            // 'reg_certificate',
            // 'voters_id'

        ],

        'C&E_INTEREST' => [
            "cne_interest_subsidy_one",
            "cne_interest_subsidy_oneA",
            "cne_interest_subsidy_oneB",
            "cne_interest_subsidy_oneB1",
            "cne_interest_subsidy_oneB2",
            "cne_interest_subsidy_oneC",
            "cne_interest_subsidy_oneC1",
            "cne_interest_subsidy_oneC2",
            "cne_interest_subsidy_oneD",
            "cne_interest_subsidy_oneD1",
            "cne_interest_subsidy_oneD2",
            "cne_interest_subsidy_two",
            "cne_interest_subsidy_twoA",
            "cne_interest_subsidy_towA1",
            "cne_interest_subsidy_twoA2",
            "cne_interest_subsidy_twoB",
            "cne_interest_subsidy_three",
            "cne_interest_subsidy_threeA",
            "cne_interest_subsidy_threeB",
            "cne_interest_subsidy_four",
            "cne_interest_subsidy_fourA",
            "cne_interest_subsidy_fourB",
            "cne_interest_subsidy_five",
            "cne_interest_subsidy_fiveA",
            "cne_interest_subsidy_fiveA1",
            "cne_interest_subsidy_fiveA2",
            "cne_interest_subsidy_fiveB",
            "cne_interest_subsidy_fiveB1",
            "cne_interest_subsidy_fiveB2",
            "cne_interest_subsidy_fiveC",
            "cne_interest_subsidy_fiveC1",
            "cne_interest_subsidy_fiveC2",
            "cne_interest_subsidy_fiveD",
            "cne_interest_subsidy_six",
            "cne_interest_subsidy_seven",
            "cne_interest_subsidy_seven1",
            "cne_interest_subsidy_seven2",
            "cne_interest_subsidy_eight",
            "cne_interest_subsidy_eightA",
            "cne_interest_subsidy_eightA1",
            "cne_interest_subsidy_eightA2",
            "cne_interest_subsidy_eightB",
            "cne_interest_subsidy_eightBTitle",
            "cne_interest_subsidy_eightBTitle1",
            "cne_interest_subsidy_eightBTitl11",
            "cne_interest_subsidy_eightBTitl12",
            "cne_interest_subsidy_eightBTitle21",
            "cne_interest_subsidy_eightBTitle22",
            "cne_interest_subsidy_nine",
            "cne_interest_subsidy_nineA",
            "cne_interest_subsidy_nineAnewUnit",
            "cne_interest_subsidy_nineAexist",
            "cne_interest_subsidy_nineAexist1",
            "cne_interest_subsidy_nineAexist2",
            "cne_interest_subsidy_nineB",
            "cne_interest_subsidy_nineB1",
            "cne_interest_subsidy_nineB1newUnit",
            "cne_interest_subsidy_nineB1exist",
            "cne_interest_subsidy_nineB1exist1",
            "cne_interest_subsidy_nineB1exist2",
            "cne_interest_subsidy_nineB2",
            "cne_interest_subsidy_nineB2newUnit",
            "cne_interest_subsidy_nineB2exist",
            "cne_interest_subsidy_nineB2exist1",
            "cne_interest_subsidy_nineB2exist2",
            "cne_interest_subsidy_nineC",
            "cne_interest_subsidy_nineCnewUnit",
            "cne_interest_subsidy_nineCexist",
            "cne_interest_subsidy_nineCexist1",
            "cne_interest_subsidy_nineCexist2",
            "cne_interest_subsidy_nineD",
            "cne_interest_subsidy_nineDnewUnit",
            "cne_interest_subsidy_nineDexist",
            "cne_interest_subsidy_nineDexist1",
            "cne_interest_subsidy_nineDexist2",
            "cne_interest_subsidy_nineE",
            "cne_interest_subsidy_nineEnewUnit",
            "cne_interest_subsidy_nineEexist",
            "cne_interest_subsidy_nineEexist1",
            "cne_interest_subsidy_nineEexist2",
            "cne_interest_subsidy_nineF",
            "cne_interest_subsidy_nineFnewUnit",
            "cne_interest_subsidy_nineFexist",
            "cne_interest_subsidy_nineFexist1",
            "cne_interest_subsidy_nineFexist2",
            "cne_interest_subsidy_totalnewUnit",
            "cne_interest_subsidy_totalexist",
            "cne_interest_subsidy_totalexist1",
            "cne_interest_subsidy_totalexist2",
            "cne_interest_subsidy_eleven",
            "cne_interest_subsidy_elevenA",
            "cne_interest_subsidy_elevenA1cne_interest_subsidy_elevenB",
            "cne_interest_subsidy_elevenB1cne_interest_subsidy_elevenB2",
            "cne_interest_subsidy_twelveA",
            "cne_interest_subsidy_twelveB",
            "cne_interest_subsidy_thirteen",
            "cne_interest_subsidy_thirteenA",
            "cne_interest_subsidy_thirteenB",
            "cne_interest_subsidy_thirteenC",
            "cne_interest_subsidy_thirteenC1",
            "cne_interest_subsidy_thirteenC2",
            "cne_interest_subsidy_fifteen",

        ],

        'POWER_NEW_CONNECTION' => [
            "power_new_connection_applicant_name",
            "power_new_connection_father_name",
            "power_new_connection_communication_address",
            "power_new_connection_communication_house",
            "power_new_connection_communication_street",
            "power_new_connection_communication_area",
            "power_new_connection_communication_district",
            "power_new_connection_connection_address",
            "power_new_connection_connection_house",
            "power_new_connection_connection_street",
            "power_new_connection_connection_area",
            "power_new_connection_connection_district",
            "power_new_connection_supply_category",
            "power_new_connection_supply_purpose",
            "power_new_connection_total_load",
            "power_new_connection_supply_type",
            "power_new_connection_is_temporary",
            "power_new_connection_temporay_from",
            "power_new_connection_temporay_to",
            "power_new_connection_is_laying_service",
            "power_new_connection_own_meter",
            // "power_new_connection_applicant_type",
            // "power_new_connection_photo",
            "power_new_connection_for",
            // "power_new_connection_identity_proof"
        ]
    ];

    const LABELS = [


        'applicant_name' => 'Applicant Name',
        'industrial_location_name' => 'Name & Location of Industrial Area',

        'communication_address' => 'Address for Communications',
        'communication_street' => 'Steet',
        'communication_city' => 'City/Town/Village',
        'communication_pin_no' => 'PIN No',
        'communication_house_no' => 'House No',
        'communication_office_phn' => 'Office Phone Number',
        'communication_residence_phn' => 'Residense Phone Number',
        'communication_mobile_phn' => 'Mobile Phone',
        'communication_email' => 'Email Address',
        'communication_website' => 'Website',
        'communication_district' => 'District',

        'proposed_or_existing' => 'Whether Proposed Or Existing Unit If Existing, Detail Address Of The Unit: Proposed/Existing.',

        'proposed_street' => 'street',
        'proposed_city' => 'city',
        'proposed_house_no' => 'House No',
        'proposed_office_phn' => 'Office No',
        'proposed_residence_phn' => 'Residence No',
        'proposed_mobile_phn' => 'Mobile No',

        'enterprise_name' => 'Name of the Enterprise',
        'enterprise_category' => 'Category Of Enterprise ',
        'nature_activity' => 'Nature Of Activity',
        'incase_others' => 'Whether The Unit Is Ancillary',
        'isAncillary' => 'Incase Of Others, Please Specify',
        'if_yes' => 'If Yes, Give Detail',
        'organization_type' => 'Type Of Organization',
        'product_manufacture' => 'Product To Be Manufacture ',
        'service_provided' => 'Service To Be Provided',
        'proposed_investment' => 'Proposed Investment In Fixed Assets (Rs. In Lakhs)',
        'installed_capacity' => 'Installed Capacity',
        'area_plot' => 'Area In Plot Required',
        'no_of_ready_build' => 'No. Of Ready Build Shed Required ',
        'electric_power' => 'Requirement Of Electric Power',
        'daily_water' => 'Daily Requirement Of Water',










        "power_new_connection_applicant_name" => "1.Name of the Applicant/Organization",
        "power_new_connection_father_name" => "2.Name of Father/ Husband/ Director/ Partner/ Trustee*",
        "power_new_connection_communication_address" => "Address for communication",
        "power_new_connection_communication_house" => "House/Plot/Premise No",
        "power_new_connection_communication_street" => "Street",
        "power_new_connection_communication_area" => "Area/Colony",
        "power_new_connection_communication_district" => "District",
        "power_new_connection_connection_address" => "Address of where the new connection is applied for/existing connection is required to be shifted",
        "power_new_connection_connection_house" => "House/Plot/Premise No",
        "power_new_connection_connection_street" => "Street",
        "power_new_connection_connection_area" => "Area/Colony",
        "power_new_connection_connection_district" => "District",
        "power_new_connection_supply_category" => "4.Category of Supply",
        "power_new_connection_supply_purpose" => "5.Purpose of Supply",
        "power_new_connection_total_load" => "6.Total Contracted Load applied for (in kW)",
        "power_new_connection_supply_type" => "7.Type of Supply",
        "power_new_connection_is_temporary" => "8.If Temporary supply, specify period of requirement",
        "power_new_connection_temporay_from" => "From (date)",
        "power_new_connection_temporay_to" => "To (date)",
        "power_new_connection_is_laying_service" => "9.Please indicate whether you want to carry out the works of laying service line and/or dedicated distribution facility for the electricity supply requisitioned.",
        "power_new_connection_own_meter" => "10.Please indicate whether you want to install your own CEA approved meter. (Yes/No)",
        // "power_new_connection_applicant_type" => "Applicant is",
        "power_new_connection_for" => "Applicant is",














        "cne_interest_subsidy_one" => "1.",
        "cne_interest_subsidy_oneA" => "A) Name Of The Unit",
        "cne_interest_subsidy_oneB" => "B) Office Address With Telephone / Mobile No. )",
        "cne_interest_subsidy_oneB1" => "1) Office Address",
        "cne_interest_subsidy_oneB2" => "",
        "cne_interest_subsidy_oneC" => "",
        "cne_interest_subsidy_oneC1" => "",
        "cne_interest_subsidy_oneC2" => "",
        "cne_interest_subsidy_oneD" => "",
        "cne_interest_subsidy_oneD1" => "",
        "cne_interest_subsidy_oneD2" => "",
        "cne_interest_subsidy_two" => "",
        "cne_interest_subsidy_twoA" => "",
        "cne_interest_subsidy_towA1" => "",
        "cne_interest_subsidy_twoA2" => "",
        "cne_interest_subsidy_twoB" => "",
        "cne_interest_subsidy_three" => "",
        "cne_interest_subsidy_threeA" => "",
        "cne_interest_subsidy_threeB" => "",
        "cne_interest_subsidy_four" => "",
        "cne_interest_subsidy_fourA" => "",
        "cne_interest_subsidy_fourB" => "",
        "cne_interest_subsidy_five" => "",
        "cne_interest_subsidy_fiveA" => "",
        "cne_interest_subsidy_fiveA1" => "",
        "cne_interest_subsidy_fiveA2" => "",
        "cne_interest_subsidy_fiveB" => "",
        "cne_interest_subsidy_fiveB1" => "",
        "cne_interest_subsidy_fiveB2" => "",
        "cne_interest_subsidy_fiveC" => "",
        "cne_interest_subsidy_fiveC1" => "",
        "cne_interest_subsidy_fiveC2" => "",
        "cne_interest_subsidy_fiveD" => "",
        "cne_interest_subsidy_six" => "",
        "cne_interest_subsidy_seven" => "",
        "cne_interest_subsidy_seven1" => "",
        "cne_interest_subsidy_seven2" => "",
        "cne_interest_subsidy_eight" => "",
        "cne_interest_subsidy_eightA" => "",
        "cne_interest_subsidy_eightA1" => "",
        "cne_interest_subsidy_eightA2" => "",
        "cne_interest_subsidy_eightB" => "",
        "cne_interest_subsidy_eightBTitle" => "",
        "cne_interest_subsidy_eightBTitle1" => "",
        "cne_interest_subsidy_eightBTitl11" => "",
        "cne_interest_subsidy_eightBTitl12" => "",
        "cne_interest_subsidy_eightBTitle21" => "",
        "cne_interest_subsidy_eightBTitle22" => "",
        "cne_interest_subsidy_nine" => "",
        "cne_interest_subsidy_nineA" => "",
        "cne_interest_subsidy_nineAnewUnit" => "",
        "cne_interest_subsidy_nineAexist" => "",
        "cne_interest_subsidy_nineAexist1" => "",
        "cne_interest_subsidy_nineAexist2" => "",
        "cne_interest_subsidy_nineB" => "",
        "cne_interest_subsidy_nineB1" => "",
        "cne_interest_subsidy_nineB1newUnit" => "",
        "cne_interest_subsidy_nineB1exist" => "",
        "cne_interest_subsidy_nineB1exist1" => "",
        "cne_interest_subsidy_nineB1exist2" => "",
        "cne_interest_subsidy_nineB2" => "",
        "cne_interest_subsidy_nineB2newUnit" => "",
        "cne_interest_subsidy_nineB2exist" => "",
        "cne_interest_subsidy_nineB2exist1" => "",
        "cne_interest_subsidy_nineB2exist2" => "",
        "cne_interest_subsidy_nineC" => "",
        "cne_interest_subsidy_nineCnewUnit" => "",
        "cne_interest_subsidy_nineCexist" => "",
        "cne_interest_subsidy_nineCexist1" => "",
        "cne_interest_subsidy_nineCexist2" => "",
        "cne_interest_subsidy_nineD" => "",
        "cne_interest_subsidy_nineDnewUnit" => "",
        "cne_interest_subsidy_nineDexist" => "",
        "cne_interest_subsidy_nineDexist1" => "",
        "cne_interest_subsidy_nineDexist2" => "",
        "cne_interest_subsidy_nineE" => "",
        "cne_interest_subsidy_nineEnewUnit" => "",
        "cne_interest_subsidy_nineEexist" => "",
        "cne_interest_subsidy_nineEexist1" => "",
        "cne_interest_subsidy_nineEexist2" => "",
        "cne_interest_subsidy_nineF" => "",
        "cne_interest_subsidy_nineFnewUnit" => "",
        "cne_interest_subsidy_nineFexist" => "",
        "cne_interest_subsidy_nineFexist1" => "",
        "cne_interest_subsidy_nineFexist2" => "",
        "cne_interest_subsidy_totalnewUnit" => "",
        "cne_interest_subsidy_totalexist" => "",
        "cne_interest_subsidy_totalexist1" => "",
        "cne_interest_subsidy_totalexist2" => "",
        "cne_interest_subsidy_eleven" => "",
        "cne_interest_subsidy_elevenA" => "",
        "cne_interest_subsidy_elevenA1cne_interest_subsidy_elevenB" => "",
        "cne_interest_subsidy_elevenB1cne_interest_subsidy_elevenB2" => "",
        "cne_interest_subsidy_twelveA" => "",
        "cne_interest_subsidy_twelveB" => "",
        "cne_interest_subsidy_thirteen" => "",
        "cne_interest_subsidy_thirteenA" => "",
        "cne_interest_subsidy_thirteenB" => "",
        "cne_interest_subsidy_thirteenC" => "",
        "cne_interest_subsidy_thirteenC1" => "",
        "cne_interest_subsidy_thirteenC2" => "",
        "cne_interest_subsidy_fifteen" => "",




    ];

    public static function getApplicationKeys($applicationCode): array
    {
        return self::APPLICATIONS[$applicationCode];
    }

    public static function getApplicationLabel(string $key): string
    {
        return self::LABELS[$key];
    }
}
